UPDATE IKR_VERSION SET SUB=2,VERSION_DATE=to_date('2011/10/31 00:00:00', 'yyyy/mm/dd hh24:mi:ss');

ALTER TABLE IKR_CATEGORY ADD THRESHOLD FLOAT(24) default '0';
ALTER TABLE IKR_CATEGORY ADD PERSISTENT NUMBER(1) default 1;
ALTER TABLE IKR_CATEGORY ADD ARCHIVE NUMBER(1) default 1;

ALTER TABLE TASK_SCHEDULER RENAME TO JOB_SCHEDULER;
ALTER TABLE TASK_ATTRIBUTE RENAME TO JOB_SCHEDULER_ATTRIBUTE;
ALTER TABLE TASK_STATIC_DOMAIN RENAME TO JOB_SCHEDULER_STATIC_DOMAIN;
ALTER TABLE TASK_ATTRIBUTE_CONFIG RENAME TO JOB_SCHEDULER_ATTRIBUTE_CONFIG;

ALTER TABLE JOB_SCHEDULER RENAME COLUMN TASK_STATIC_DOMAIN_ID TO JOB_SCHEDULER_STATIC_DOMAIN_ID;
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE RENAME COLUMN TASK_SCHEDULER_ID TO JOB_SCHEDULER_ID;
ALTER TABLE JOB_SCHEDULER_STATIC_DOMAIN RENAME COLUMN TASK_TYPE TO JOB_SCHEDULER_TYPE;
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG RENAME COLUMN TASK_STATIC_DOMAIN_ID TO JOB_SCHEDULER_STATIC_DOMAIN_ID;

TRUNCATE TABLE IKR_VALUE;
TRUNCATE TABLE IKR_DEFINITION;
TRUNCATE TABLE ALERT_DEFINITION;
TRUNCATE TABLE ALERT_CONDITION;
TRUNCATE TABLE ALERT_COMPUTE;
TRUNCATE TABLE ALERT_EVENT;
TRUNCATE TABLE ALERT_EVENT_COMMENT;
TRUNCATE TABLE ALERT_EVENT_COMPUTE;
TRUNCATE TABLE ALERT_VALIDITY;
TRUNCATE TABLE USER_ALERT_ACTION;
TRUNCATE TABLE SNMP_ALERT_ACTION;

delete from IKR_STATIC_DOMAIN where DOMAIN_VALUE like 'COMPUTED - %';

delete from MONITOR_ACTIVITY where IKR_CATEGORY_RESOURCE_ID in (select ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_CATEGORY where IKR_STATIC_DOMAIN_ID in (select IKR_STATIC_DOMAIN_ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_STATIC_DOMAIN where ID in (select IKR_STATIC_DOMAIN_ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO');
delete from METRIC_DOMAIN_RESOURCE where RESOURCE_NAME = 'THREAD_INFO';