TRUNCATE TABLE ACCESS_PERM;

TRUNCATE TABLE IKR_USER;

TRUNCATE TABLE USER_LOGIN;

TRUNCATE TABLE ALERT_LEVEL;

TRUNCATE TABLE ALERT_GROUP;

TRUNCATE TABLE ALERT_DOMAIN;

TRUNCATE TABLE ALERT_SUB_DOMAIN;

TRUNCATE TABLE REPORT_TYPE VALUES;

TRUNCATE TABLE REPORT_CONFIG;

TRUNCATE TABLE INDIKTOR_ID;

TRUNCATE TABLE IKR_VERSION ;