DROP TABLE IF EXISTS `IKR_VERSION`;
CREATE TABLE `IKR_VERSION` (
  `MAJOR` int(10) unsigned NOT NULL,
  `MINOR` int(10) unsigned NOT NULL,
  `SUB` int(10) unsigned NOT NULL,
  `VERSION_DATE` datetime NOT NULL,
  `PATCH_VERSION` int(10) unsigned NOT NULL,
  `PATCH_DATE` datetime NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CONNECTOR_CONFIG`;
CREATE TABLE `CONNECTOR_CONFIG` (
  `ID` bigint(20) unsigned NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `CONNECTOR_TYPE` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(255) default NULL,
  `MAX_ATTEMPT` smallint unsigned,
  `ATTEMPT_DELAY` smallint unsigned,
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CONNECTOR_CONFIG_ATTRIBUTE`;
CREATE TABLE `CONNECTOR_CONFIG_ATTRIBUTE` (
  `CONNECTOR_CONFIG_ID` bigint(20) unsigned NOT NULL,
  `ATTR_LABEL` varchar(100) NOT NULL,
  `ATTR_VALUE` varchar(100) NOT NULL,
   PRIMARY KEY  (`CONNECTOR_CONFIG_ID`,`ATTR_LABEL`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CONNECTOR_BINDING`;
CREATE TABLE `CONNECTOR_BINDING` (
  `MONITOR_ID` bigint(20) unsigned NOT NULL,
  `CONNECTOR_CONFIG_ID` bigint(20) unsigned NOT NULL,
   PRIMARY KEY  (`MONITOR_ID`,`CONNECTOR_CONFIG_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG`;
CREATE TABLE `METRIC_DOMAIN_CONFIG` (
  `ID` bigint(20) unsigned NOT NULL, 
  `CONNECTOR_TYPE` varchar(255) NOT NULL,  
  `IKR_STATIC_DOMAIN_ID` int(10) unsigned NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,   
  `CLASSNAME` varchar(100) NOT NULL,  
  `SYNC_USE` tinyint(1) default '0',
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG_ATTRIBUTE`;
CREATE TABLE `METRIC_DOMAIN_CONFIG_ATTRIBUTE` (
  `METRIC_DOMAIN_CONFIG_ID` bigint(20) unsigned NOT NULL,
  `ATTRIBUTE_KEY` varchar(255) NOT NULL,
  `ATTRIBUTE_VALUE` varchar(255) default NULL,
  PRIMARY KEY  (`METRIC_DOMAIN_CONFIG_ID`,`ATTRIBUTE_KEY`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG_ITEMS`;
CREATE TABLE `METRIC_DOMAIN_CONFIG_ITEMS` (
  `METRIC_DOMAIN_CONFIG_ID` int(10) unsigned NOT NULL,
  `ITEM_VALUE` varchar(255) NOT NULL,
   PRIMARY KEY  (`METRIC_DOMAIN_CONFIG_ID`, `ITEM_VALUE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG_EXTENSION`;
CREATE TABLE `METRIC_DOMAIN_CONFIG_EXTENSION` (
  `METRIC_DOMAIN_CONFIG_ID` bigint(20) unsigned NOT NULL,
  `PRIORITY` int(10) unsigned NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,   
  `CLASSNAME` varchar(100) NOT NULL,  
   PRIMARY KEY (METRIC_DOMAIN_CONFIG_ID, PRIORITY)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `METRIC_DOMAIN_RESOURCE`;
CREATE TABLE `METRIC_DOMAIN_RESOURCE` (
  `ID` bigint(20) unsigned NOT NULL, 
  `IKR_STATIC_DOMAIN_ID` bigint(20) unsigned NOT NULL,  
  `RESOURCE_NAME` varchar(100) NOT NULL,
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG_RESOURCES`;
CREATE TABLE `METRIC_DOMAIN_CONFIG_RESOURCES` (
  `METRIC_DOMAIN_CONFIG_ID` bigint(20) unsigned NOT NULL,
  `METRIC_DOMAIN_RESOURCE_ID` bigint(20) unsigned NOT NULL,
  `ENABLED` tinyint(1) default '1',
  PRIMARY KEY  (`METRIC_DOMAIN_CONFIG_ID`,`METRIC_DOMAIN_RESOURCE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `INDIKTOR_ID`;
CREATE TABLE `INDIKTOR_ID` (
  `ID` bigint(20) unsigned NOT NULL,
  `OBJECT_TYPE` varchar(100) NOT NULL,
   PRIMARY KEY  (`OBJECT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `IKR_STATIC_DOMAIN`;
CREATE TABLE `IKR_STATIC_DOMAIN` (
  `ID` int(10) unsigned NOT NULL,
  `PARENT_ID` bigint(20) unsigned NOT NULL,
  `DOMAIN_VALUE` varchar(100) NOT NULL,
  `DOMAIN_LABEL` varchar(100) default NULL,
  `DESCRIPTION` varchar(4000) default NULL,
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG_FIELDS`;
CREATE TABLE `METRIC_DOMAIN_CONFIG_FIELDS` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `METRIC_DOMAIN_CONFIG_ID` bigint(20) unsigned NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `LABEL` varchar(100) NOT NULL,
  `FIELD_TYPE` varchar(100) default 'inputText',
  `FIELD_TYPE_VALUES` varchar(1024) default NULL,
  `ENABLE` tinyint(1) default '0',
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `IKR_CATEGORY`;
CREATE TABLE `IKR_CATEGORY` (
  `IKR_STATIC_DOMAIN_ID` int(10) unsigned NOT NULL,
  `UNIT_TYPE` varchar(100) NOT NULL,
  `UNIT` varchar(100) default NULL,
  `THRESHOLD` double unsigned default '0',
  `PERSISTENT` tinyint(1) default '1',
  `ARCHIVE` tinyint(1) default '1',
  `SEARCH_INDEXES` varchar(4000) default NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `LOGICAL_ENV`;
CREATE TABLE `LOGICAL_ENV` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `IKR_CATEGORY_RESOURCE`;
CREATE TABLE `IKR_CATEGORY_RESOURCE` (
  `ID` int(10) unsigned NOT NULL,
  `IKR_STATIC_DOMAIN_ID` int(10) NOT NULL,
  `METRIC_DOMAIN_RESOURCE_ID` int(10) unsigned NOT NULL,
  `NAME` varchar(150) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `MONITOR`;
CREATE TABLE `MONITOR` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `NAME` varchar(200) default NULL,
  `LOGICAL_ENV_ID` int(10) unsigned NOT NULL,
  `METRIC_DOMAIN_CONFIG_ID` int(20) unsigned NOT NULL, 
  `STARTED` tinyint(1) default '0',
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `MONITOR_ACTIVITY`;
CREATE TABLE `MONITOR_ACTIVITY` (
  `MONITOR_ID` int(20) unsigned NOT NULL,
  `IKR_CATEGORY_RESOURCE_ID` int(20) unsigned NOT NULL,
  `ENABLE` tinyint(1) default '0',
  PRIMARY KEY  (`MONITOR_ID`,`IKR_CATEGORY_RESOURCE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `MONITOR_SCHEDULER`;
CREATE TABLE `MONITOR_SCHEDULER` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `MONITOR_ID` int(20) unsigned NOT NULL,
  `CAPTURE_DELAY` int(10) unsigned default 0,
  `SCHEDULING_TYPE` varchar(200) NOT NULL,
  `SCHEDULING_MODE` varchar(200) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER`;
CREATE TABLE `JOB_SCHEDULER` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `NAME` varchar(200) NOT NULL,
  `LOGICAL_ENV_ID` int(10) unsigned NOT NULL,
  `JOB_SCHEDULER_STATIC_DOMAIN_ID` bigint(20) NOT NULL,
  `SCHEDULING_MODE` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(500) default NULL,
  `ACTIVE` tinyint(1) default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER_ATTRIBUTE`;
CREATE TABLE `JOB_SCHEDULER_ATTRIBUTE` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `JOB_SCHEDULER_ID` int(20) unsigned NOT NULL,
  `NAME` varchar(200) NOT NULL,
  `ATTR_VALUE` varchar(200) default NULL, 
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER_STATIC_DOMAIN`;
CREATE TABLE `JOB_SCHEDULER_STATIC_DOMAIN` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `JOB_SCHEDULER_TYPE` varchar(100) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(250) default NULL,
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER_ATTRIBUTE_CONFIG`;
CREATE TABLE `JOB_SCHEDULER_ATTRIBUTE_CONFIG` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `JOB_SCHEDULER_STATIC_DOMAIN_ID` bigint(20) unsigned NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `LABEL` varchar(100) NOT NULL,
  `SELECTION` tinyint(1) default '0',
  `ENABLE` tinyint(1) default '0',
  `SELECTION_VALUE` varchar(100) default NULL, 
   PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `MONITOR_SCHEDULER_TIME`;
CREATE TABLE `MONITOR_SCHEDULER_TIME` (
  `MONITOR_SCHEDULER_ID` int(20) unsigned NOT NULL,
  `SCHED_TIME_TYPE` varchar(200) NOT NULL,
  `SCHED_DAY` int(10) unsigned default 0,
  `SCHED_HOUR` int(10) unsigned default 0,
  `SCHED_MIN` int(10) unsigned default 0,
  PRIMARY KEY (`MONITOR_SCHEDULER_ID`, `SCHED_TIME_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `MONITOR_SCHEDULER_EXEC`;
CREATE TABLE `MONITOR_SCHEDULER_EXEC` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `MONITOR_SCHEDULER_ID` int(20) unsigned NOT NULL,
  `START_TIME` datetime NOT NULL,
  `END_TIME` datetime default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER_TIME`;
CREATE TABLE `JOB_SCHEDULER_TIME` (
  `JOB_ID` int(20) unsigned NOT NULL,
  `SCHED_TIME_TYPE` varchar(200) NOT NULL,
  `SCHED_DAY` int(10) unsigned default 0,
  `SCHED_HOUR` int(10) unsigned default 0,
  `SCHED_MIN` int(10) unsigned default 0,
  PRIMARY KEY (`JOB_ID`, `SCHED_TIME_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER_EXEC`;
CREATE TABLE `JOB_SCHEDULER_EXEC` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `JOB_ID` int(20) unsigned NOT NULL,
  `START_TIME` datetime NOT NULL,
  `END_TIME` datetime default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `MONITOR_ATTRIBUTE`;
CREATE TABLE `MONITOR_ATTRIBUTE` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `MONITOR_ID` int(20) unsigned NOT NULL,
  `NAME` varchar(200) NOT NULL,
  `ATTR_VALUE` varchar(200) NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `IKR_DEFINITION`;
CREATE TABLE `IKR_DEFINITION` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `MONITOR_ID` bigint(20) NOT NULL,
  `IKR_INSTANCE` longtext default NULL,
  `IKR_COMPUTE` varchar(100) default NULL,  
  `IKR_CATEGORY_ID`  bigint(20) unsigned NOT NULL,
  `LOGICAL_ENV_ID` int(10) unsigned NOT NULL,  
  `CROSS_COMPUTE` varchar(150) default NULL, 
  `SD_VALUE` VARCHAR(100) default NULL,  
  `ENABLE` tinyint(1) default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `IKR_VALUE`;
CREATE TABLE `IKR_VALUE` (
  `ID` bigint(20) unsigned NOT NULL,
  `IKR_DEFINITION_ID` bigint(20) unsigned NOT NULL,
  `CAPTURE_TIME` datetime NOT NULL,
  `VALUE` longtext,
  PRIMARY KEY  (`ID`),
  KEY `IDX_IKR_DEFINITION_ID` (`IKR_DEFINITION_ID`),
  KEY `IDX_CAPTURE_TIME` USING HASH (`CAPTURE_TIME`)
) ENGINE=MyISAM AUTO_INCREMENT=5899402 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `IKR_VALUE_ARCHIVE`;
CREATE TABLE `IKR_VALUE_ARCHIVE` (
  `ID` bigint(20) unsigned NOT NULL,
  `IKR_DEFINITION_ID` bigint(20) unsigned NOT NULL,
  `CAPTURE_TIME` datetime NOT NULL,
  `VALUE` longtext,
  PRIMARY KEY  (`ID`),
  KEY `IDX_IKR_DEFINITION_ID_ARCH` (`IKR_DEFINITION_ID`),
  KEY `IDX_CAPTURE_TIME_ARCH` USING HASH (`CAPTURE_TIME`)
) ENGINE=MyISAM AUTO_INCREMENT=5899402 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `USER_LOGIN`;
CREATE TABLE `USER_LOGIN` (
  `ID` bigint(20) unsigned NOT NULL,
  `LOGIN` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) default NULL,
  PRIMARY KEY  (`ID`,`LOGIN`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `IKR_USER`;
CREATE TABLE `IKR_USER` (
  `ID` bigint(20) unsigned NOT NULL,
  `FIRSTNAME` varchar(255) NOT NULL,
  `LASTNAME` varchar(255) default NULL,
  `EMAIL` varchar(255) default NULL,
  `PHONE1` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ACCESS_PERM`;
CREATE TABLE `ACCESS_PERM` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `NAME` varchar(50) default NULL,
  `DESCRIPTION` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ROLE_ACCESS_PERM`;
CREATE TABLE `ROLE_ACCESS_PERM` (
  `ROLE_ID` bigint(20) unsigned NOT NULL,
  `ACCESS_PERM_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY  (`ROLE_ID`,`ACCESS_PERM_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `USER_ROLE`;
CREATE TABLE `USER_ROLE` (
  `USER_ID` bigint(20) unsigned NOT NULL,
  `ROLE_ID` bigint(20) unsigned NOT NULL,
  PRIMARY KEY  (`USER_ID`,`ROLE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_DEFINITION`;
CREATE TABLE `ALERT_DEFINITION` (
  `ID` bigint(20) unsigned NOT NULL,
  `NAME` varchar(255) default NULL,
  `ALERT_GROUP_ID` bigint(20) unsigned NOT NULL,
  `DOMAIN_ID` bigint(20) unsigned NOT NULL,
  `SUB_DOMAIN_ID` bigint(20) unsigned NOT NULL,
  `LOGICAL_ENV_ID` int(10) unsigned NOT NULL,
  `DESCRIPTION` varchar(255) default NULL,
  `HOW_TO` varchar(255) default NULL,
  `CREATION_DATE` datetime NOT NULL,
  `LAST_UPDATE_DATE` datetime NOT NULL,
  `ENABLE` tinyint(1) default '0',
  `RAISING_DELAY` bigint(20) unsigned default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_VALIDITY`;
CREATE TABLE `ALERT_VALIDITY` (
	`ALERT_DEFINITION_ID` bigint(20) unsigned NOT NULL,
	`ALERT_VALIDITY_ID` int(10) unsigned default 0,
	`VALIDITY_TIME_TYPE` varchar(50) NOT NULL,
	`VALIDITY_HOUR` int(10) unsigned default 0,
	`VALIDITY_MIN` int(10) unsigned default 0
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `ALERT_WORKFLOW_FILTER`;
CREATE TABLE `ALERT_WORKFLOW_FILTER` (
  `ALERT_DEFINITION_ID` bigint(20) unsigned NOT NULL,
  `WORKFLOW` varchar(50) default NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_LEVEL`;
CREATE TABLE `ALERT_LEVEL` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `NAME` varchar(255) default NULL,
  `ALERT_VALUE` int(10) unsigned NOT NULL default 0,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_GROUP`;
CREATE TABLE `ALERT_GROUP` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `GROUP_VALUE` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_DOMAIN`;
CREATE TABLE `ALERT_DOMAIN` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `ALERT_GROUP_ID` bigint(20) unsigned NOT NULL,
  `DOMAIN_VALUE` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_SUB_DOMAIN`;
CREATE TABLE `ALERT_SUB_DOMAIN` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `ALERT_DOMAIN_ID` bigint(20) unsigned NOT NULL,
  `SUB_DOMAIN_VALUE` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_CONDITION`;
CREATE TABLE `ALERT_CONDITION` (
  `ID` int(10) unsigned NOT NULL default 0,
  `ALERT_DEFINITION_ID` int(20) default NULL,
  `IKR_DEFINITION_ID` int(20) default NULL,
  `COND_UNIT_TYPE` VARCHAR(50) default 'NUMBER',
  `COND_UNIT` VARCHAR(50) default 'NUMBER',
  `COND_VALUE` varchar(200) default NULL,
  `COND_OPERATOR` varchar(200) NOT NULL,
  `ENABLE` tinyint(1) default '0',
  PRIMARY KEY  (`ALERT_DEFINITION_ID`,`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_COMPUTE`;
CREATE TABLE `ALERT_COMPUTE` (
  `ALERT_DEFINITION_ID` int(20) default NULL,
  `SEVERITY` int(10) unsigned NOT NULL default 0,
  `LABEL` varchar(255) default NULL,
  `CAUSE` varchar(100) default NULL,
  `ENABLE` tinyint(1) default '0',
  PRIMARY KEY  (`ALERT_DEFINITION_ID`,`SEVERITY`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_ACTION`;
CREATE TABLE `ALERT_ACTION` (
  `ID` bigint(20) NOT NULL,
  `ALERT_DEFINITION_ID` int(20) NOT NULL,
  `ACTION_TYPE` varchar(50) default NULL,
  `ENABLE` tinyint(1) default '0',
  PRIMARY KEY  (`ID`, `ALERT_DEFINITION_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `USER_ALERT_ACTION`;
CREATE TABLE `USER_ALERT_ACTION` (
  `ID` bigint(20) NOT NULL,
  `ALERT_DEFINITION_ID` int(20) NOT NULL,
  `RECIPIENT_ID` bigint(20) unsigned NOT NULL default 0,
  `RECIPIENT_TYPE` varchar(10) NOT NULL,
  PRIMARY KEY  (`ID`, `ALERT_DEFINITION_ID`, `RECIPIENT_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SNMP_ALERT_ACTION`;
CREATE TABLE `SNMP_ALERT_ACTION` (
  `ID` bigint(20) NOT NULL,
  `ALERT_DEFINITION_ID` int(20) NOT NULL,
  `SNMP_CONFIG_ID` bigint(20) unsigned NOT NULL default 0,
  PRIMARY KEY  (`ID`, `ALERT_DEFINITION_ID`, `SNMP_CONFIG_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `SNMP_CONFIG`;
CREATE TABLE `SNMP_CONFIG` (
		`ID` bigint(20) unsigned NOT NULL auto_increment,
		`NAME` VARCHAR(255) NOT NULL,
		`VERSION` bigint(20) default 1,
		`COMMUNITY` VARCHAR(255) default NULL,
		`HOSTNAME` VARCHAR(255) NOT NULL,
		`PORT` bigint(20) NOT NULL,
		`GENERIC_TYPE` bigint(20) NOT NULL,
		`SPECIFIC_TYPE` bigint(20) NOT NULL,
		`USERNAME` VARCHAR(255) default NULL,
		`AUTH_PROTOCOL` VARCHAR(255) default NULL,
		`AUTH_PASSWORD` VARCHAR(255) default NULL,
		`PRIV_PROTOCOL` VARCHAR(255) default NULL,
		`PRIV_PASSWORD` VARCHAR(255) default NULL,
		`CONTEXT_NAME` VARCHAR(255) default NULL,
		`ENGINE_ID` VARCHAR(255) default NULL,
		PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_EVENT`;
CREATE TABLE `ALERT_EVENT` (
  `ID` bigint(20) unsigned NOT NULL,
  `ALERT_DEFINITION_ID` bigint(20) unsigned NOT NULL,
  `EVENT_DATE` datetime NOT NULL,
  `EVENT_TYPE` varchar(20) default NULL,    
  `OLD_WORKFLOW` varchar(50) default NULL,
  `NEW_WORKFLOW` varchar(50) default NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_EVENT_COMMENT`;
CREATE TABLE `ALERT_EVENT_COMMENT` (
  `ALERT_EVENT_ID` bigint(20) unsigned NOT NULL,
  `COMMENTS` longtext default null,
  `USER_ID` bigint(20) unsigned NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ALERT_EVENT_COMPUTE`;
CREATE TABLE `ALERT_EVENT_COMPUTE` (
  `ALERT_EVENT_ID` bigint(20) unsigned NOT NULL,
  `SEVERITY` int(10) unsigned NOT NULL default 0,
  `STATUS` varchar(50) default NULL,
  `IKR_VALUE_IDS` varchar(250) default NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `REPORT_CONFIG`;
CREATE TABLE `REPORT_CONFIG` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `REPORT_TYPE_ID` bigint(20) unsigned NOT NULL,
  `NAME` varchar(200) default NULL,
  `DESCRIPTION` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `REPORT_TYPE`;
CREATE TABLE `REPORT_TYPE` (
  `ID` bigint(20) unsigned NOT NULL auto_increment,
  `NAME` varchar(200) default NULL,
  `DESCRIPTION` varchar(255) default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;