/*
* CLEAN THREAD_INFO METRIC INFORMATION
*/

delete from IKR_DEFINITION where IKR_CATEGORY_ID in (select IKR_STATIC_DOMAIN_ID from ikr_category_resource where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from MONITOR_ACTIVITY where IKR_CATEGORY_RESOURCE_ID in (select ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_CATEGORY where IKR_STATIC_DOMAIN_ID in (select IKR_STATIC_DOMAIN_ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_STATIC_DOMAIN where ID in (select IKR_STATIC_DOMAIN_ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO');
delete from METRIC_DOMAIN_RESOURCE where RESOURCE_NAME = 'THREAD_INFO';


/*
* TABLE MODELE UPGRADE
*/

CREATE TABLE IKR_VALUE_ARCHIVE (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   IKR_DEFINITION_ID NUMBER(20) NOT NULL,
  	   CAPTURE_TIME DATE NOT NULL,
  	   VALUE CLOB
) TABLESPACE INDIKTOR;

CREATE INDEX IKR_VALUE_IDX_ARCH ON IKR_VALUE_ARCHIVE(IKR_DEFINITION_ID,CAPTURE_TIME) LOGGING NOPARALLEL TABLESPACE INDIKTOR;

ALTER TABLE IKR_CATEGORY ADD THRESHOLD FLOAT(24) default '0';
ALTER TABLE IKR_CATEGORY ADD PERSISTENT NUMBER(1) default 1;
ALTER TABLE IKR_CATEGORY ADD ARCHIVE NUMBER(1) default 1;
ALTER TABLE IKR_CATEGORY ADD SEARCH_INDEXES varchar(4000) default NULL;

ALTER TABLE TASK_SCHEDULER RENAME TO JOB_SCHEDULER;
ALTER TABLE TASK_ATTRIBUTE RENAME TO JOB_SCHEDULER_ATTRIBUTE;
ALTER TABLE TASK_STATIC_DOMAIN RENAME TO JOB_SCHEDULER_STATIC_DOMAIN;
ALTER TABLE TASK_ATTRIBUTE_CONFIG RENAME TO JOB_SCHEDULER_ATTRIBUTE_CONFIG;

ALTER TABLE JOB_SCHEDULER RENAME COLUMN TASK_STATIC_DOMAIN_ID TO JOB_SCHEDULER_STATIC_DOMAIN_ID;
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE RENAME COLUMN TASK_SCHEDULER_ID TO JOB_SCHEDULER_ID;
ALTER TABLE JOB_SCHEDULER_STATIC_DOMAIN RENAME COLUMN TASK_TYPE TO JOB_SCHEDULER_TYPE;
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG RENAME COLUMN TASK_STATIC_DOMAIN_ID TO JOB_SCHEDULER_STATIC_DOMAIN_ID;

ALTER TABLE JOB_SCHEDULER DROP COLUMN ACTION;

ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION NUMBER(1) default 0;
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION_VALUE VARCHAR(100) default NULL;

DROP SEQUENCE TASK_SCHEDULER_ID_SEQ;
DROP TRIGGER TASK_SCHEDULER_TRIGGER;

CREATE SEQUENCE JOB_SCHEDULER_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER JOB_SCHEDULER_TRIGGER
BEFORE INSERT ON JOB_SCHEDULER
for each row
begin
    select JOB_SCHEDULER_ID_SEQ.nextval into :new.id from dual;
end;
/

DROP SEQUENCE TASK_ATTRIBUTE_ID_SEQ;
DROP TRIGGER TASK_ATTRIBUTE_TRIGGER;

CREATE SEQUENCE JOB_SCHEDULER_ATTRIBUTE_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER JOB_SCHEDULER_ATTRIBUTE_TRIGGER
BEFORE INSERT ON JOB_SCHEDULER_ATTRIBUTE
for each row
begin
    select JOB_SCHEDULER_ATTRIBUTE_ID_SEQ.nextval into :new.id from dual;
end;
/

DROP SEQUENCE TASK_STATIC_DOMAIN_ID_SEQ;
DROP TRIGGER TASK_STATIC_DOMAIN_TRIGGER;

CREATE SEQUENCE JOB_SCHEDULER_STATIC_DOMAIN_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER JOB_SCHEDULER_STATIC_DOMAIN_TRIGGER
BEFORE INSERT ON JOB_SCHEDULER_STATIC_DOMAIN
for each row
begin
    select JOB_SCHEDULER_STATIC_DOMAIN_ID_SEQ.nextval into :new.id from dual;
end;
/

DROP SEQUENCE TASK_ATTRIBUTE_CONFIG_ID_SEQ;
DROP TRIGGER TASK_ATTRIBUTE_CONFIG_TRIGGER;

CREATE SEQUENCE JOB_SCHEDULER_ATTRIBUTE_CONFIG_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER JOB_SCHEDULER_ATTRIBUTE_CONFIG_TRIGGER
BEFORE INSERT ON JOB_SCHEDULER_ATTRIBUTE_CONFIG
for each row
begin
    select JOB_SCHEDULER_ATTRIBUTE_CONFIG_ID_SEQ.nextval into :new.id from dual;
end;
/

ALTER TABLE SCHEDULER_TIME RENAME TO MONITOR_SCHEDULER_TIME;
ALTER TABLE SCHEDULER_EXEC RENAME TO MONITOR_SCHEDULER_EXEC;

ALTER TABLE MONITOR_SCHEDULER_TIME RENAME COLUMN SCHEDULER_ID TO MONITOR_SCHEDULER_ID;
ALTER TABLE MONITOR_SCHEDULER_EXEC RENAME COLUMN SCHEDULER_ID TO MONITOR_SCHEDULER_ID;

ALTER TABLE MONITOR_SCHEDULER_TIME DROP CONSTRAINT PK_SCHEDULER_TIME;
ALTER TABLE MONITOR_SCHEDULER_TIME ADD CONSTRAINT PK_MONITOR_SCHEDULER_TIME PRIMARY KEY (MONITOR_SCHEDULER_ID, SCHED_TIME_TYPE);

DROP SEQUENCE SCHEDULER_EXEC_ID_SEQ;
DROP TRIGGER SCHEDULER_EXEC_TRIGGER;

CREATE SEQUENCE MONITOR_SCHEDULER_EXEC_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER MONITOR_SCHEDULER_EXEC_TRIGGER
BEFORE INSERT ON MONITOR_SCHEDULER_EXEC
for each row
begin
    select MONITOR_SCHEDULER_EXEC_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE JOB_SCHEDULER_TIME (
		JOB_ID NUMBER(20) NOT NULL,
		SCHED_TIME_TYPE VARCHAR(200) NOT NULL,
		SCHED_DAY NUMBER(10) default 0,
		SCHED_HOUR NUMBER(10) default 0,
		SCHED_MIN NUMBER(10) default 0,
   CONSTRAINT PK_JOB_SCHEDULER_TIME PRIMARY KEY (JOB_ID, SCHED_TIME_TYPE)
) TABLESPACE INDIKTOR;

CREATE TABLE JOB_SCHEDULER_EXEC (
		ID NUMBER(10) NOT NULL PRIMARY KEY,
		JOB_ID NUMBER(20) NOT NULL,
		START_TIME DATE NOT NULL,
		END_TIME DATE default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE JOB_SCHEDULER_EXEC_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER JOB_SCHEDULER_EXEC_TRIGGER
BEFORE INSERT ON JOB_SCHEDULER_EXEC
for each row
begin
    select JOB_SCHEDULER_EXEC_ID_SEQ.nextval into :new.id from dual;
end;
/

/*
* TABLE INITIALISATION
*/
INSERT INTO JOB_SCHEDULER_STATIC_DOMAIN VALUES (1,'PURGE_TABLE','Ikr Table Purge Scheduler',NULL);

INSERT INTO JOB_SCHEDULER_ATTRIBUTE_CONFIG VALUES (1,1,'PURGE_FREQUENCY','Purge Frequency',1,1,'Day-1:Week-1:Month-1');
INSERT INTO JOB_SCHEDULER_ATTRIBUTE_CONFIG VALUES (2,1,'ARCHIVE_NEEDED','Archive Needed ?',1,1,'true:false');
INSERT INTO JOB_SCHEDULER_ATTRIBUTE_CONFIG VALUES (3,1,'VALUES_PER_DAY','Values per Day',1,1,'1:2:4:6:12:24');

INSERT INTO INDIKTOR_ID VALUES (1,'IkrValueArchive');

UPDATE IKR_VERSION SET SUB=2,VERSION_DATE=to_date('2011/11/02 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),PATCH_VERSION=1;
