UPDATE IKR_VERSION SET SUB=2, VERSION_DATE='2012-02-03 00:00:00', PATCH_VERSION=5;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG_ATTRIBUTE`;
CREATE TABLE `METRIC_DOMAIN_CONFIG_ATTRIBUTE` (
  `METRIC_DOMAIN_CONFIG_ID` bigint(20) unsigned NOT NULL,
  `ATTRIBUTE_KEY` varchar(255) NOT NULL,
  `ATTRIBUTE_VALUE` varchar(255) default NULL,
  PRIMARY KEY  (`METRIC_DOMAIN_CONFIG_ID`,`ATTRIBUTE_KEY`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE IKR_CATEGORY_RESOURCE CHANGE ID ID int(10) unsigned NOT NULL;

INSERT INTO `INDIKTOR_ID` VALUES (1000,'IkrCategoryResource');