UPDATE IKR_VERSION SET SUB=2, VERSION_DATE='2012-01-17 00:00:00', PATCH_VERSION=4;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION DROP COLUMN EXT_ID;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION DROP COLUMN EXTENDED_ID;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION DROP COLUMN EXT_CONNECTOR_TYPE;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION CHANGE EXT_DESCRIPTION DESCRIPTION varchar(255) NOT NULL;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION CHANGE EXT_CLASSNAME CLASSNAME varchar(255) NOT NULL;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION ADD METRIC_DOMAIN_CONFIG_ID bigint(20) unsigned NOT NULL;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION ADD PRIORITY int(10) unsigned NOT NULL;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION ADD PRIMARY KEY (METRIC_DOMAIN_CONFIG_ID, PRIORITY);

ALTER TABLE METRIC_DOMAIN_ITEMS RENAME TO METRIC_DOMAIN_CONFIG_ITEMS;

DROP TABLE IF EXISTS `METRIC_DOMAIN_CONFIG_RESOURCES`;
CREATE TABLE `METRIC_DOMAIN_CONFIG_RESOURCES` (
  `METRIC_DOMAIN_CONFIG_ID` bigint(20) unsigned NOT NULL,
  `METRIC_DOMAIN_RESOURCE_ID` bigint(20) unsigned NOT NULL,
  `ENABLED` tinyint(1) default '1',
  PRIMARY KEY  (`METRIC_DOMAIN_CONFIG_ID`,`METRIC_DOMAIN_RESOURCE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE METRIC_DOMAIN_CONFIG ADD SYNC_USE tinyint(1) default '0';

ALTER TABLE METRIC_DOMAIN_CONFIG_FIELDS ADD FIELD_TYPE varchar(100) default 'inputText';
ALTER TABLE METRIC_DOMAIN_CONFIG_FIELDS ADD FIELD_TYPE_VALUES varchar(1024) default NULL;

ALTER TABLE ALERT_EVENT_COMMENT CHANGE COMMENTS COMMENTS longtext default null;
