UPDATE IKR_VERSION SET SUB=2, VERSION_DATE='2011-12-13 00:00:00', PATCH_VERSION=3;

TRUNCATE TABLE ALERT_EVENT;
TRUNCATE TABLE ALERT_EVENT_COMMENT;
TRUNCATE TABLE ALERT_EVENT_COMPUTE;

ALTER TABLE ALERT_EVENT ADD ID bigint(20) unsigned NOT NULL;

ALTER TABLE ALERT_EVENT_COMMENT DROP COLUMN ALERT_DEFINITION_ID;
ALTER TABLE ALERT_EVENT_COMMENT DROP COLUMN EVENT_DATE;
ALTER TABLE ALERT_EVENT_COMMENT ADD ALERT_EVENT_ID bigint(20) unsigned NOT NULL;

ALTER TABLE ALERT_EVENT_COMPUTE DROP COLUMN ALERT_DEFINITION_ID;
ALTER TABLE ALERT_EVENT_COMPUTE DROP COLUMN EVENT_DATE;
ALTER TABLE ALERT_EVENT_COMPUTE ADD ALERT_EVENT_ID bigint(20) unsigned NOT NULL;

INSERT INTO `INDIKTOR_ID` VALUES (1,'AlertEvent');

