INSERT INTO `ACCESS_PERM` VALUES (10,'DashBoard - Visualisation',NULL);
INSERT INTO `ACCESS_PERM` VALUES (11,'DashBoard - View AlertBoard Detail',NULL);

INSERT INTO `ACCESS_PERM` VALUES (20,'Alert Center Access',NULL);
INSERT INTO `ACCESS_PERM` VALUES (21,'Alert Center - Board',NULL);
INSERT INTO `ACCESS_PERM` VALUES (22,'Alert Center - Board - View Alert Detail',NULL);
INSERT INTO `ACCESS_PERM` VALUES (23,'Alert Center - Board - Validate an Alert',NULL);
INSERT INTO `ACCESS_PERM` VALUES (24,'Alert Center - Definition',NULL);
INSERT INTO `ACCESS_PERM` VALUES (25,'Alert Center - Definition - View an Alert',NULL);
INSERT INTO `ACCESS_PERM` VALUES (26,'Alert Center - Definition - Create New Alert',NULL);
INSERT INTO `ACCESS_PERM` VALUES (27,'Alert Center - Definition - Modify an Alert',NULL);
INSERT INTO `ACCESS_PERM` VALUES (28,'Alert Center - Definition - delete an Alert',NULL);
INSERT INTO `ACCESS_PERM` VALUES (29,'Alert Center - Definition - Modify Alert Conditions',NULL);
INSERT INTO `ACCESS_PERM` VALUES (30,'Alert Center - Definition - Modify Alert Computations',NULL);
INSERT INTO `ACCESS_PERM` VALUES (31,'Alert Center - Definition - Modify Alert TimeSlot',NULL);
INSERT INTO `ACCESS_PERM` VALUES (32,'Alert Center - Definition - Modify Alert Notifications',NULL);

INSERT INTO `ACCESS_PERM` VALUES (40,'Data Center Access',NULL);
INSERT INTO `ACCESS_PERM` VALUES (41,'Data Center - Analysis',NULL);
INSERT INTO `ACCESS_PERM` VALUES (42,'Data Center - Analysis - Export File',NULL);
INSERT INTO `ACCESS_PERM` VALUES (43,'Data Center - Domain',NULL);
INSERT INTO `ACCESS_PERM` VALUES (44,'Data Center - Domain - Create New Domain',NULL);
INSERT INTO `ACCESS_PERM` VALUES (45,'Data Center - Domain - Modify Domain',NULL);
INSERT INTO `ACCESS_PERM` VALUES (46,'Data Center - Domain - Delete Domain',NULL);
INSERT INTO `ACCESS_PERM` VALUES (47,'Data Center - Cross Compute',NULL);
INSERT INTO `ACCESS_PERM` VALUES (48,'Data Center - Cross Compute - Create New Cross Compute',NULL);
INSERT INTO `ACCESS_PERM` VALUES (49,'Data Center - Cross Compute - Modify Cross Compute',NULL);
INSERT INTO `ACCESS_PERM` VALUES (50,'Data Center - Cross Compute - Delete Cross Compute',NULL);
INSERT INTO `ACCESS_PERM` VALUES (51,'Data Center - Static Data',NULL);
INSERT INTO `ACCESS_PERM` VALUES (52,'Data Center - Static Data - Create New Static Data',NULL);
INSERT INTO `ACCESS_PERM` VALUES (53,'Data Center - Static Data - Modify Static Data',NULL);
INSERT INTO `ACCESS_PERM` VALUES (54,'Data Center - Static Data - Delete Static Data',NULL);

INSERT INTO `ACCESS_PERM` VALUES (60,'Report Center Access',NULL);

INSERT INTO `ACCESS_PERM` VALUES (80,'Admin Access',NULL);
INSERT INTO `ACCESS_PERM` VALUES (81,'Admin - Dashboard - Update',NULL);
INSERT INTO `ACCESS_PERM` VALUES (82,'Admin - Dashboard - Delete a Dashboard',NULL);
INSERT INTO `ACCESS_PERM` VALUES (83,'Admin - Dashboard - Add New Dashboard Component',NULL);
INSERT INTO `ACCESS_PERM` VALUES (84,'Admin - Dashboard - Delete Dashboard Component',NULL);
INSERT INTO `ACCESS_PERM` VALUES (85,'Admin - Dashboard - Modify Dashboard Component',NULL);
INSERT INTO `ACCESS_PERM` VALUES (86,'Admin - Dashboard - New',NULL);
INSERT INTO `ACCESS_PERM` VALUES (87,'Admin - Data Collection - Logical Env',NULL);
INSERT INTO `ACCESS_PERM` VALUES (88,'Admin - Data Collection - Logical Env - Delete Logical Env',NULL);
INSERT INTO `ACCESS_PERM` VALUES (89,'Admin - Data Collection - Logical Env - Modify Logical Env',NULL);
INSERT INTO `ACCESS_PERM` VALUES (90,'Admin - Data Collection - Logical Env - Add New Logical Env',NULL);
INSERT INTO `ACCESS_PERM` VALUES (91,'Admin - Data Collection - Monitor',NULL);
INSERT INTO `ACCESS_PERM` VALUES (92,'Admin - Data Collection - Monitor - Delete Monitor',NULL);
INSERT INTO `ACCESS_PERM` VALUES (93,'Admin - Data Collection - Monitor - Modify Monitor',NULL);
INSERT INTO `ACCESS_PERM` VALUES (94,'Admin - Data Collection - Monitor - Duplicate Monitor',NULL);
INSERT INTO `ACCESS_PERM` VALUES (95,'Admin - Data Collection - Monitor - Add New Monitor',NULL);
INSERT INTO `ACCESS_PERM` VALUES (96,'Admin - Data Collection - Monitor - Activate or Deactivate a Metric',NULL);
INSERT INTO `ACCESS_PERM` VALUES (97,'Admin - Data Collection - Monitor - Modify Metric',NULL);
INSERT INTO `ACCESS_PERM` VALUES (98,'Admin - Data Collection - Monitor - Add Metric Compute',NULL);
INSERT INTO `ACCESS_PERM` VALUES (99,'Admin - Data Collection - Monitor - Add New Metric',NULL);
INSERT INTO `ACCESS_PERM` VALUES (100,'Admin - Data Collection - Connector',NULL);
INSERT INTO `ACCESS_PERM` VALUES (101,'Admin - Data Collection - Connector - Delete Connector',NULL);
INSERT INTO `ACCESS_PERM` VALUES (102,'Admin - Data Collection - Connector - Modify Connector',NULL);
INSERT INTO `ACCESS_PERM` VALUES (103,'Admin - Data Collection - Connector - Duplicate Connector',NULL);
INSERT INTO `ACCESS_PERM` VALUES (104,'Admin - Data Collection - Connector - Add New Connector',NULL);
INSERT INTO `ACCESS_PERM` VALUES (105,'Admin - Data Collection - Scheduled Task',NULL);
INSERT INTO `ACCESS_PERM` VALUES (106,'Admin - Data Collection - Scheduled Task - Delete Scheduled Task',NULL);
INSERT INTO `ACCESS_PERM` VALUES (107,'Admin - Data Collection - Scheduled Task - Modify Scheduled Task',NULL);
INSERT INTO `ACCESS_PERM` VALUES (108,'Admin - Data Collection - Scheduled Task - Duplicate Scheduled Task',NULL);
INSERT INTO `ACCESS_PERM` VALUES (109,'Admin - Data Collection - Scheduled Task - Add New Scheduled Task',NULL);
INSERT INTO `ACCESS_PERM` VALUES (110,'Admin - Third Party - SNMP Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (111,'Admin - Third Party - SNMP Config - Delete SNMP Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (112,'Admin - Third Party - SNMP Config - Modify SNMP Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (113,'Admin - Third Party - SNMP Config - Duplicate SNMP Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (114,'Admin - Third Party - SNMP Config - Add New SNMP Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (115,'Admin - Security - User',NULL);
INSERT INTO `ACCESS_PERM` VALUES (116,'Admin - Security - User - Delete User',NULL);
INSERT INTO `ACCESS_PERM` VALUES (117,'Admin - Security - User - Modify User',NULL);
INSERT INTO `ACCESS_PERM` VALUES (118,'Admin - Security - User - Duplicate User',NULL);
INSERT INTO `ACCESS_PERM` VALUES (119,'Admin - Security - User - Reset User Login',NULL);
INSERT INTO `ACCESS_PERM` VALUES (120,'Admin - Security - User - Add New User',NULL);
INSERT INTO `ACCESS_PERM` VALUES (121,'Admin - Security - Role',NULL);
INSERT INTO `ACCESS_PERM` VALUES (122,'Admin - Security - Role - Delete Role',NULL);
INSERT INTO `ACCESS_PERM` VALUES (123,'Admin - Security - Role - Modify Role',NULL);
INSERT INTO `ACCESS_PERM` VALUES (124,'Admin - Security - Role - Add New Role',NULL);
INSERT INTO `ACCESS_PERM` VALUES (125,'Admin - Extension - Metric Domain Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (126,'Admin - Extension - Metric Domain Config - Delete Metric Domain Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (128,'Admin - Extension - Metric Domain Config - Modify Metric Domain Config',NULL);
INSERT INTO `ACCESS_PERM` VALUES (129,'Admin - Extension - Metric Domain Config - Add New Metric Domain Config',NULL);

INSERT INTO `ACCESS_PERM` VALUES (1000,'Settings - Password - Modify Password',NULL);

INSERT INTO `IKR_USER` VALUES (1,'admin','admin', NULL, NULL);

INSERT INTO `USER_LOGIN` VALUES (1,'admin','ZD21BNrpmVU=');
UPDATE `USER_LOGIN` set PASSWORD='0mtg/vdDkMwGGV3BqXVgvQ==' where LOGIN not in ('admin');

INSERT INTO `ALERT_LEVEL` VALUES (1, 'LOW', 1), (2, 'MEDIUM', 2), (3, 'HIGH', 3);

INSERT INTO `ALERT_GROUP` VALUES (1, 'CALYPSO'), (2, 'PROCESS'), (3, 'SYSTEM'), (4, 'DBMS - SYBASE'), (5, 'DBMS - ORACLE'), (6, 'TRADE PROCESSING'), (7, 'BACK OFFICE OPERATIONS'), (8, 'EXCEPTIONS');

INSERT INTO `ALERT_DOMAIN` VALUES (1, 1, 'DATASERVER');
INSERT INTO `ALERT_DOMAIN` VALUES (2, 1, 'ENGINE');
INSERT INTO `ALERT_DOMAIN` VALUES (3, 1, 'WORKFLOW');
INSERT INTO `ALERT_DOMAIN` VALUES (4, 1, 'TASK');
INSERT INTO `ALERT_DOMAIN` VALUES (5, 1, 'EVENTSERVER');
INSERT INTO `ALERT_DOMAIN` VALUES (6, 1, 'SCHEDULED TASK');
INSERT INTO `ALERT_DOMAIN` VALUES (7, 1, 'SECURITY');
INSERT INTO `ALERT_DOMAIN` VALUES (8, 2, 'AVAILABILITY');
INSERT INTO `ALERT_DOMAIN` VALUES (9, 2, 'LOW PERFORMANCE');
INSERT INTO `ALERT_DOMAIN` VALUES (10, 2, 'DEADLOCK');
INSERT INTO `ALERT_DOMAIN` VALUES (11, 2, 'IDLE MODE');
INSERT INTO `ALERT_DOMAIN` VALUES (12, 3, 'LOW PERFORMANCE');
INSERT INTO `ALERT_DOMAIN` VALUES (13, 3, 'DISK ISSUE');
INSERT INTO `ALERT_DOMAIN` VALUES (14, 3, 'NETWORK');
INSERT INTO `ALERT_DOMAIN` VALUES (15, 3, 'SERVER AVAILABILITY');
INSERT INTO `ALERT_DOMAIN` VALUES (16, 8, 'EXCEPTIONS');
INSERT INTO `ALERT_DOMAIN` VALUES (17, 6, 'TRADE PROCESSING');
INSERT INTO `ALERT_DOMAIN` VALUES (18, 7, 'ACCOUNTING');
INSERT INTO `ALERT_DOMAIN` VALUES (19, 7, 'SETTLEMENTS');
INSERT INTO `ALERT_DOMAIN` VALUES (20, 7, 'CONFIRMATIONS');
INSERT INTO `ALERT_DOMAIN` VALUES (21, 7, 'POSITIONS');
INSERT INTO `ALERT_DOMAIN` VALUES (22, 7, 'TRANSFER');

INSERT INTO `ALERT_SUB_DOMAIN` VALUES (1, 1, 'CACHE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (2, 1, 'CONNECTIONS OVERLOAD');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (3, 1, 'LOST CONNECTION');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (4, 1, 'EVENT POOL BUFFER');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (5, 2, 'STUCK EVENTS');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (6, 2, 'UNCONSUMED EVENTS');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (7, 2, 'EVENT POOL BUFFER');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (8, 2, 'BATCH MODE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (9, 2, 'CACHE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (10, 8, 'AVAILABILITY');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (11, 3, 'WORKFLOW');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (12, 4, 'TASK');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (13, 5, 'EVENT POOL BUFFER');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (14, 6, 'TASK IN DELAY');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (15, 6, 'FAILED TASK');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (16, 6, 'TASK TOO LONG');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (17, 7, 'SECURITY');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (18, 9, 'LOW PERFORMANCE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (19, 10, 'DEADLOCK');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (20, 11, 'IDLE MODE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (21, 12, 'LOW PERFORMANCE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (22, 13, 'DISK ISSUE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (23, 14, 'TCP');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (24, 14, 'INTERFACE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (25, 15, 'SERVER AVAILABILITY');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (26, 18, 'ACCOUNTING');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (27, 19, 'SETTLEMENTS');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (28, 20, 'CONFIRMATIONS');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (29, 21, 'POSITIONS');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (30, 22, 'TRANSFER');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (31, 17, 'TRADE');
INSERT INTO `ALERT_SUB_DOMAIN` VALUES (32, 17, 'CASH FLOWS');

INSERT INTO `REPORT_TYPE` VALUES (1,'CPU GLOBAL','GLOBAL CPU FOR CALYPSO DS.2 hours span is advised');

INSERT INTO `REPORT_CONFIG` VALUES (1,1,'Hyppo',NULL),(2,1,'Pelican',NULL);

INSERT INTO `INDIKTOR_ID` VALUES (1,'IkrValue');
INSERT INTO `INDIKTOR_ID` VALUES (1,'AlertDefinition');
INSERT INTO `INDIKTOR_ID` VALUES (2,'User');
INSERT INTO `INDIKTOR_ID` VALUES (1,'Connector');
INSERT INTO `INDIKTOR_ID` VALUES (1,'StaticData');
INSERT INTO `INDIKTOR_ID` VALUES (1,'MetricDomainConfig');
INSERT INTO `INDIKTOR_ID` VALUES (1,'StaticDomain');
INSERT INTO `INDIKTOR_ID` VALUES (1,'MetricDomainResource');

INSERT INTO `IKR_VERSION` VALUES (1, 5, 0, '2011-06-13 00:00:00', 000, NULL);

