UPDATE IKR_VERSION SET SUB=3,VERSION_DATE=to_date('2012/03/22 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),PATCH_VERSION=3;

DELETE FROM IKR_DEFINITION WHERE MONITOR_ID NOT IN (SELECT ID FROM MONITOR) and MONITOR_ID NOT IN (0, -1)
