CREATE TABLE IKR_VERSION(
  MAJOR NUMBER(10) NOT NULL,
  MINOR NUMBER(10) NOT NULL,
  SUB NUMBER(10) NOT NULL,
  VERSION_DATE DATE NOT NULL,
  PATCH_VERSION NUMBER(10) NOT NULL,
  PATCH_DATE DATE NULL
) TABLESPACE INDIKTOR;

CREATE TABLE CONNECTOR_CONFIG (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   NAME VARCHAR(100) NOT NULL,
  	   CONNECTOR_TYPE VARCHAR(100) NOT NULL,
  	   DESCRIPTION VARCHAR(255) NOT NULL,
  	   MAX_ATTEMPT NUMBER(10) NOT NULL,	   
  	   ATTEMPT_DELAY NUMBER(10) NOT NULL   
) TABLESPACE INDIKTOR;

CREATE TABLE CONNECTOR_CONFIG_ATTRIBUTE (
	CONNECTOR_CONFIG_ID NUMBER(20) NOT NULL,
	ATTR_LABEL  VARCHAR(100) NOT NULL,
	ATTR_VALUE  VARCHAR(100)  default NULL,
   CONSTRAINT PK_CONNECTOR_CONFIG_ATTRIBUTE PRIMARY KEY (CONNECTOR_CONFIG_ID, ATTR_LABEL)
) TABLESPACE INDIKTOR;

CREATE TABLE CONNECTOR_BINDING (
  MONITOR_ID NUMBER(20) NOT NULL,
  CONNECTOR_CONFIG_ID NUMBER(20) NOT NULL,
  CONSTRAINT PK_CONNECTOR_BINDING PRIMARY KEY (MONITOR_ID, CONNECTOR_CONFIG_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE METRIC_DOMAIN_CONFIG (
   ID NUMBER(20) NOT NULL PRIMARY KEY,
   CONNECTOR_TYPE VARCHAR(255),
   IKR_STATIC_DOMAIN_ID  NUMBER(10) NOT NULL,
   DESCRIPTION VARCHAR(255) NOT NULL,   
   CLASSNAME VARCHAR(100) NOT NULL
) TABLESPACE INDIKTOR;

CREATE TABLE METRIC_DOMAIN_ITEMS (
   METRIC_DOMAIN_CONFIG_ID  NUMBER(10) NOT NULL,
   ITEM_VALUE VARCHAR(255) NOT NULL,
   CONSTRAINT PK_METRIC_DOMAIN_ITEMS PRIMARY KEY (METRIC_DOMAIN_CONFIG_ID, ITEM_VALUE)
) TABLESPACE INDIKTOR;

CREATE TABLE METRIC_DOMAIN_CONFIG_EXTENSION (
   EXT_ID NUMBER(20) NOT NULL PRIMARY KEY,
   EXTENDED_ID NUMBER(20),
   EXT_CONNECTOR_TYPE VARCHAR(255),
   EXT_DESCRIPTION VARCHAR(255) NOT NULL,   
   EXT_CLASSNAME VARCHAR(100) NOT NULL
) TABLESPACE INDIKTOR;

CREATE TABLE METRIC_DOMAIN_RESOURCE (
  ID NUMBER(20) NOT NULL PRIMARY KEY, 
  IKR_STATIC_DOMAIN_ID NUMBER(20) NOT NULL,  
  RESOURCE_NAME VARCHAR(100) NOT NULL
) TABLESPACE INDIKTOR;

CREATE TABLE INDIKTOR_ID (
	ID NUMBER(20) NOT NULL,
  	OBJECT_TYPE VARCHAR(100) NOT NULL PRIMARY KEY
) TABLESPACE INDIKTOR;

CREATE TABLE IKR_STATIC_DOMAIN (
  	ID NUMBER(20) NOT NULL PRIMARY KEY,
  	PARENT_ID NUMBER(20) NOT NULL,
	DOMAIN_VALUE varchar(100) NOT NULL,
	DOMAIN_LABEL varchar(100) default NULL,
	DESCRIPTION varchar(4000) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE METRIC_DOMAIN_CONFIG_FIELDS (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   METRIC_DOMAIN_CONFIG_ID NUMBER(20) NOT NULL,
  	   NAME VARCHAR(100) NOT NULL,
  	   LABEL VARCHAR(100) NOT NULL,
  	   ENABLE NUMBER(1) default 0
) TABLESPACE INDIKTOR;

CREATE SEQUENCE CONFIG_FIELD_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER CONFIG_FIELD_TRIGGER
BEFORE INSERT ON METRIC_DOMAIN_CONFIG_FIELDS
for each row
begin
    select CONFIG_FIELD_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE IKR_CATEGORY (
  	IKR_STATIC_DOMAIN_ID NUMBER(10) NOT NULL,
	UNIT_TYPE VARCHAR(100) NOT NULL,
	UNIT VARCHAR(100) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE LOGICAL_ENV (
  ID NUMBER(10) NOT NULL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE LOGICAL_ENV_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER LOGICAL_ENV_TRIGGER
BEFORE INSERT ON LOGICAL_ENV
for each row
begin
    select LOGICAL_ENV_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE IKR_CATEGORY_RESOURCE (
  ID NUMBER(10) NOT NULL PRIMARY KEY,
  IKR_STATIC_DOMAIN_ID NUMBER(10) NOT NULL,
  METRIC_DOMAIN_RESOURCE_ID NUMBER(10) NOT NULL,
  NAME VARCHAR(150) NOT NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE IKR_CATEGORY_RESOURCE_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER IKR_CATEGORY_RESOURCE_TRIGGER
BEFORE INSERT ON IKR_CATEGORY_RESOURCE
for each row
begin
    select IKR_CATEGORY_RESOURCE_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE MONITOR (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   NAME VARCHAR(200) default NULL,
  	   LOGICAL_ENV_ID NUMBER(10) NOT NULL,
  	   METRIC_DOMAIN_CONFIG_ID NUMBER(20) NOT NULL,
  	   STARTED NUMBER(1) default 0
) TABLESPACE INDIKTOR;

CREATE SEQUENCE MONITOR_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER MONITOR_TRIGGER
BEFORE INSERT ON MONITOR
for each row
begin
    select MONITOR_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE MONITOR_ACTIVITY (
	MONITOR_ID NUMBER(20) NOT NULL,
	IKR_CATEGORY_RESOURCE_ID NUMBER(20) NOT NULL,
	ENABLE NUMBER(1) default 0,
	CONSTRAINT PK_MONITOR_ACTIVITY PRIMARY KEY (MONITOR_ID, IKR_CATEGORY_RESOURCE_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE MONITOR_SCHEDULER (
		ID NUMBER(10) NOT NULL PRIMARY KEY,
		MONITOR_ID NUMBER(20) NOT NULL,
		CAPTURE_DELAY NUMBER(10) default 0,
		SCHEDULING_TYPE VARCHAR(200) NOT NULL,
		SCHEDULING_MODE VARCHAR(200) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE MONITOR_SCHEDULER_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER MONITOR_SCHEDULER_TRIGGER
BEFORE INSERT ON MONITOR_SCHEDULER
for each row
begin
    select MONITOR_SCHEDULER_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE TASK_SCHEDULER (
		ID NUMBER(10) NOT NULL PRIMARY KEY,
		NAME VARCHAR(200) NOT NULL,
		LOGICAL_ENV_ID NUMBER(10) NOT NULL,
		ACTION VARCHAR(100) NOT NULL,
		TASK_STATIC_DOMAIN_ID NUMBER(20) NOT NULL,
		SCHEDULING_MODE VARCHAR(100) NOT NULL,
		DESCRIPTION VARCHAR(500) default NULL,
		ACTIVE NUMBER(1) default 0
) TABLESPACE INDIKTOR;

CREATE SEQUENCE TASK_SCHEDULER_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER TASK_SCHEDULER_TRIGGER
BEFORE INSERT ON TASK_SCHEDULER
for each row
begin
    select TASK_SCHEDULER_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE TASK_ATTRIBUTE (
		ID NUMBER(10) NOT NULL PRIMARY KEY,
		TASK_SCHEDULER_ID NUMBER(20) NOT NULL,
		NAME VARCHAR(200) NOT NULL,
		ATTR_VALUE VARCHAR(200) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE TASK_ATTRIBUTE_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER TASK_ATTRIBUTE_TRIGGER
BEFORE INSERT ON TASK_ATTRIBUTE
for each row
begin
    select TASK_ATTRIBUTE_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE TASK_STATIC_DOMAIN (
		ID NUMBER(20) NOT NULL PRIMARY KEY,
		TASK_TYPE VARCHAR(100) NOT NULL,
		NAME VARCHAR(100) NOT NULL,
		DESCRIPTION VARCHAR(250) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE TASK_STATIC_DOMAIN_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER TASK_STATIC_DOMAIN_TRIGGER
BEFORE INSERT ON TASK_STATIC_DOMAIN
for each row
begin
    select TASK_STATIC_DOMAIN_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE TASK_ATTRIBUTE_CONFIG (
		ID NUMBER(20) NOT NULL PRIMARY KEY,
		TASK_STATIC_DOMAIN_ID NUMBER(20) NOT NULL,
		NAME VARCHAR(100) NOT NULL,
		LABEL VARCHAR(100) NOT NULL,
		ENABLE NUMBER(1) default 0
)  TABLESPACE INDIKTOR;

CREATE SEQUENCE TASK_ATTRIBUTE_CONFIG_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER TASK_ATTRIBUTE_CONFIG_TRIGGER
BEFORE INSERT ON TASK_ATTRIBUTE_CONFIG
for each row
begin
    select TASK_ATTRIBUTE_CONFIG_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE SCHEDULER_TIME (
		SCHEDULER_ID NUMBER(20) NOT NULL,
		SCHED_TIME_TYPE VARCHAR(200) NOT NULL,
		SCHED_DAY NUMBER(10) default 0,
		SCHED_HOUR NUMBER(10) default 0,
		SCHED_MIN NUMBER(10) default 0,
   CONSTRAINT PK_SCHEDULER_TIME PRIMARY KEY (SCHEDULER_ID, SCHED_TIME_TYPE)
) TABLESPACE INDIKTOR;

CREATE TABLE SCHEDULER_EXEC (
		ID NUMBER(10) NOT NULL PRIMARY KEY,
		SCHEDULER_ID NUMBER(20) NOT NULL,
		START_TIME DATE NOT NULL,
		END_TIME DATE default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE SCHEDULER_EXEC_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER SCHEDULER_EXEC_TRIGGER
BEFORE INSERT ON SCHEDULER_EXEC
for each row
begin
    select SCHEDULER_EXEC_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE MONITOR_ATTRIBUTE (
  	   ID NUMBER(10) NOT NULL  PRIMARY KEY,
  	   MONITOR_ID NUMBER(20) NOT NULL,
  	   NAME VARCHAR(200) NOT NULL,
  	   ATTR_VALUE VARCHAR(200) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE MONITOR_ATTRIBUTE_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER MONITOR_ATTRIBUTE_TRIGGER
BEFORE INSERT ON MONITOR_ATTRIBUTE
for each row
begin
    select MONITOR_ATTRIBUTE_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE IKR_DEFINITION (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   MONITOR_ID NUMBER(20) NOT NULL,
  	   IKR_INSTANCE VARCHAR(4000) default NULL,
	   IKR_COMPUTE VARCHAR(100) default NULL,  
  	   IKR_CATEGORY_ID  NUMBER(20) NOT NULL,
	   LOGICAL_ENV_ID NUMBER(10) NOT NULL,  
	   CROSS_COMPUTE VARCHAR(150) default NULL,  
  	   ENABLE NUMBER(1) default 0
) TABLESPACE INDIKTOR;

CREATE INDEX IKR_DEFINITION_INST_ENV_IDX ON IKR_DEFINITION (IKR_INSTANCE, LOGICAL_ENV_ID) LOGGING NOPARALLEL TABLESPACE INDIKTOR;
CREATE INDEX IKR_DEFINITION_MONITOR_ID_IDX ON IKR_DEFINITION (MONITOR_ID) LOGGING NOPARALLEL TABLESPACE INDIKTOR;
CREATE SEQUENCE IKR_DEFINITION_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER IKR_DEFINITION_TRIGGER
BEFORE INSERT ON IKR_DEFINITION
for each row
begin
    select IKR_DEFINITION_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE IKR_VALUE (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   IKR_DEFINITION_ID NUMBER(20) NOT NULL,
  	   CAPTURE_TIME DATE NOT NULL,
  	   VALUE CLOB
) TABLESPACE INDIKTOR;

CREATE INDEX IKR_VALUE_IDX ON IKR_VALUE(IKR_DEFINITION_ID,CAPTURE_TIME) LOGGING NOPARALLEL TABLESPACE INDIKTOR;

CREATE TABLE USER_LOGIN (
  	   ID NUMBER(20) NOT NULL,
  	   LOGIN VARCHAR(255) NOT NULL,
  	   PASSWORD VARCHAR(255) default NULL,
	 CONSTRAINT PK_USER_LOGIN PRIMARY KEY (ID, LOGIN)
) TABLESPACE INDIKTOR;

CREATE TABLE IKR_USER (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   FIRSTNAME VARCHAR(255) NOT NULL,
  	   LASTNAME VARCHAR(255) default NULL,
  	   EMAIL VARCHAR(255) default NULL,
  	   PHONE1 VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE ACCESS_PERM (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   NAME VARCHAR(255) NOT NULL,
  	   DESCRIPTION VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE ROLE (
  	  ID NUMBER(20) NOT NULL PRIMARY KEY,
  	  NAME VARCHAR(50) default NULL,
  	  DESCRIPTION VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE ROLE_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER ROLE_TRIGGER
BEFORE INSERT ON ROLE
for each row
begin
    select ROLE_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE ROLE_ACCESS_PERM (
  	   ROLE_ID NUMBER(20) NOT NULL,
  	   ACCESS_PERM_ID NUMBER(10) NOT NULL,
	 CONSTRAINT PK_ROLE_ACCESS_PERM PRIMARY KEY (ROLE_ID, ACCESS_PERM_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE USER_ROLE (
  	   USER_ID NUMBER(20) NOT NULL,
  	   ROLE_ID NUMBER(20) NOT NULL,
	  CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_DEFINITION (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   NAME VARCHAR(255) default NULL,
  	   ALERT_GROUP_ID NUMBER(20) NOT NULL,
  	   DOMAIN_ID NUMBER(20) NOT NULL,
  	   SUB_DOMAIN_ID NUMBER(20) NOT NULL,
  	   LOGICAL_ENV_ID NUMBER(10) default NULL,
  	   DESCRIPTION VARCHAR(255) default NULL,
  	   HOW_TO VARCHAR(255) default NULL,
  	   CREATION_DATE DATE NOT NULL,
  	   LAST_UPDATE_DATE DATE NOT NULL,
  	   ENABLE NUMBER(1) default 0,
	   RAISING_DELAY NUMBER(20) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_VALIDITY (
	ALERT_DEFINITION_ID NUMBER(20) NOT NULL,
	ALERT_VALIDITY_ID NUMBER(10) default 0,
	VALIDITY_TIME_TYPE VARCHAR(50) NOT NULL,
	VALIDITY_HOUR NUMBER(10) default 0,
	VALIDITY_MIN NUMBER(10) default 0
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_WORKFLOW_FILTER (
  ALERT_DEFINITION_ID NUMBER(20) NOT NULL,
  WORKFLOW VARCHAR(50) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_LEVEL (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   NAME VARCHAR(255) default NULL,
  	   ALERT_VALUE NUMBER(10) default 0
) TABLESPACE INDIKTOR;

CREATE SEQUENCE ALERT_LEVEL_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER ALERT_LEVEL_TRIGGER
BEFORE INSERT ON ALERT_LEVEL
for each row
begin
    select ALERT_LEVEL_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE ALERT_GROUP (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
	   GROUP_VALUE VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE ALERT_GROUP_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER ALERT_GROUP_TRIGGER
BEFORE INSERT ON ALERT_GROUP
for each row
begin
    select ALERT_GROUP_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE ALERT_DOMAIN (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   ALERT_GROUP_ID NUMBER(20) NOT NULL,
  	   DOMAIN_VALUE VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE ALERT_DOMAIN_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER ALERT_DOMAIN_TRIGGER
BEFORE INSERT ON ALERT_DOMAIN
for each row
begin
    select ALERT_DOMAIN_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE ALERT_SUB_DOMAIN (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   ALERT_DOMAIN_ID NUMBER(20) NOT NULL,
  	   SUB_DOMAIN_VALUE VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE ALERT_SUB_DOMAIN_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER ALERT_SUB_DOMAIN_TRIGGER
BEFORE INSERT ON ALERT_SUB_DOMAIN
for each row
begin
    select ALERT_SUB_DOMAIN_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE ALERT_CONDITION (
  	   ID NUMBER(10) default 0,
  	   ALERT_DEFINITION_ID NUMBER(20) default NULL,
  	   IKR_DEFINITION_ID NUMBER(20) default NULL, 
  	   COND_VALUE VARCHAR(200) default NULL,
	   COND_OPERATOR VARCHAR(200) NOT NULL,
  	   ENABLE NUMBER(1) default 0,
	  CONSTRAINT PK_ALERT_CONDITION PRIMARY KEY (ID, ALERT_DEFINITION_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_COMPUTE (
  	   ALERT_DEFINITION_ID NUMBER(20) default NULL,
  	   SEVERITY NUMBER(10) default 0,
  	   LABEL VARCHAR(255) default NULL,
  	   CAUSE VARCHAR(100) default NULL,
  	   ENABLE NUMBER(1) default 0,
	 CONSTRAINT PK_ALERT_COMPUTE PRIMARY KEY (ALERT_DEFINITION_ID, SEVERITY)
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_ACTION (
  	   ID NUMBER(20) NOT NULL,
  	   ALERT_DEFINITION_ID NUMBER(20) default NULL,
  	   ACTION_TYPE VARCHAR(50) default NULL,
  	   ENABLE NUMBER(1) default '0',
	   CONSTRAINT PK_ALERT_ACTION PRIMARY KEY (ID, ALERT_DEFINITION_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE USER_ALERT_ACTION (
  	   ID NUMBER(20) NOT NULL,
	   ALERT_DEFINITION_ID NUMBER(20) NOT NULL,
  	   RECIPIENT_ID NUMBER(20) default 0,
  	   RECIPIENT_TYPE VARCHAR(10) NOT NULL,
	 CONSTRAINT PK_USER_ALERT_ACTION PRIMARY KEY (ID,ALERT_DEFINITION_ID,RECIPIENT_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE SNMP_ALERT_ACTION (
  	   ID NUMBER(20) NOT NULL,
	   ALERT_DEFINITION_ID NUMBER(20) NOT NULL,
  	   SNMP_CONFIG_ID NUMBER(20) default 0,
	 CONSTRAINT PK_SNMP_ALERT_ACTION PRIMARY KEY (ID, ALERT_DEFINITION_ID,SNMP_CONFIG_ID)
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_EVENT (
		ALERT_DEFINITION_ID NUMBER(20) NOT NULL,
		EVENT_DATE DATE NOT NULL,
		EVENT_TYPE varchar(20) default NULL,    
		OLD_WORKFLOW varchar(50) default NULL,
		NEW_WORKFLOW varchar(50) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_EVENT_COMMENT (
		ALERT_DEFINITION_ID NUMBER(20) NOT NULL,
		EVENT_DATE DATE NOT NULL,
		COMMENTS varchar(255) default NULL,
		USER_ID NUMBER(20) NOT NULL
) TABLESPACE INDIKTOR;

CREATE TABLE ALERT_EVENT_COMPUTE (
		ALERT_DEFINITION_ID NUMBER(20) NOT NULL,
		EVENT_DATE DATE NOT NULL,
		SEVERITY NUMBER(10) NOT NULL,
		STATUS varchar(50) default NULL,
		IKR_VALUE_IDS varchar(255) default NULL
) TABLESPACE INDIKTOR;

CREATE TABLE REPORT_CONFIG (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   REPORT_TYPE_ID NUMBER(20) NOT NULL,
  	   NAME VARCHAR(200) default NULL,
  	   DESCRIPTION VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE REPORT_CONFIG_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER REPORT_CONFIG_TRIGGER
BEFORE INSERT ON REPORT_CONFIG
for each row
begin
    select REPORT_CONFIG_ID_SEQ.nextval into :new.id from dual;
end;
/


CREATE TABLE REPORT_TYPE (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   NAME VARCHAR(200) default NULL,
  	   DESCRIPTION VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE REPORT_TYPE_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER REPORT_TYPE_TRIGGER
BEFORE INSERT ON REPORT_TYPE
for each row
begin
    select REPORT_TYPE_ID_SEQ.nextval into :new.id from dual;
end;
/

CREATE TABLE SNMP_CONFIG (
		ID NUMBER(20) NOT NULL PRIMARY KEY,
		NAME VARCHAR(255) NOT NULL,
		VERSION NUMBER(20) default '1',
		COMMUNITY VARCHAR(255) default NULL,
		HOSTNAME VARCHAR(255) NOT NULL,
		PORT NUMBER(20) NOT NULL,
		GENERIC_TYPE NUMBER(20) NOT NULL,
		SPECIFIC_TYPE NUMBER(20) NOT NULL,
		USERNAME VARCHAR(255) default NULL,
		AUTH_PROTOCOL VARCHAR(255) default NULL,
		AUTH_PASSWORD VARCHAR(255) default NULL,
		PRIV_PROTOCOL VARCHAR(255) default NULL,
		PRIV_PASSWORD VARCHAR(255) default NULL,
		CONTEXT_NAME VARCHAR(255) default NULL,
		ENGINE_ID VARCHAR(255) default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE SNMP_CONFIG_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER SNMP_CONFIG_TRIGGER
BEFORE INSERT ON SNMP_CONFIG
for each row
begin
    select SNMP_CONFIG_ID_SEQ.nextval into :new.id from dual;
end;
/

/*   ALTER FOR MONITOR DELETION    */
ALTER TABLE CONNECTOR_BINDING ADD CONSTRAINT FK_CONNECTOR_BINDING FOREIGN KEY (MONITOR_ID) REFERENCES MONITOR (ID) ON DELETE CASCADE;
ALTER TABLE MONITOR_ACTIVITY ADD CONSTRAINT FK_MONITOR_ACTIVITY FOREIGN KEY (MONITOR_ID) REFERENCES MONITOR (ID) ON DELETE CASCADE;
ALTER TABLE MONITOR_ATTRIBUTE ADD CONSTRAINT FK_MONITOR_ATTRIBUTE FOREIGN KEY (MONITOR_ID) REFERENCES MONITOR (ID) ON DELETE CASCADE;
ALTER TABLE MONITOR_SCHEDULER ADD CONSTRAINT FK_MONITOR_SCHEDULER FOREIGN KEY (MONITOR_ID) REFERENCES MONITOR (ID) ON DELETE CASCADE;
ALTER TABLE SCHEDULER_TIME ADD CONSTRAINT FK_MONITOR_ID FOREIGN KEY (SCHEDULER_ID) REFERENCES MONITOR (ID) ON DELETE CASCADE;

/*   ALTER FOR DOMAIN DELETION    */
ALTER TABLE IKR_CATEGORY ADD CONSTRAINT FK_IKR_CATEGORY FOREIGN KEY (IKR_STATIC_DOMAIN_ID) REFERENCES IKR_STATIC_DOMAIN (ID) ON DELETE CASCADE;

/*   ALTER FOR SCHEDULER DELETION    */
ALTER TABLE TASK_ATTRIBUTE ADD CONSTRAINT FK_TASK_ATTRIBUTE FOREIGN KEY (TASK_SCHEDULER_ID) REFERENCES TASK_SCHEDULER (ID) ON DELETE CASCADE;
ALTER TABLE SCHEDULER_TIME ADD CONSTRAINT FK_TASK_SCHEDULER FOREIGN KEY (SCHEDULER_ID) REFERENCES TASK_SCHEDULER (ID) ON DELETE CASCADE;

/*   ALTER FOR ACTION   */
ALTER TABLE USER_ALERT_ACTION DROP CONSTRAINT PK_USER_ALERT_ACTION;
ALTER TABLE USER_ALERT_ACTION ADD CONSTRAINT PK_USER_ALERT_ACTION PRIMARY KEY (ID, ALERT_DEFINITION_ID, RECIPIENT_ID);
ALTER TABLE SNMP_ALERT_ACTION DROP CONSTRAINT PK_SNMP_ALERT_ACTION;
ALTER TABLE SNMP_ALERT_ACTION ADD CONSTRAINT PK_SNMP_ALERT_ACTION PRIMARY KEY (ID, ALERT_DEFINITION_ID, SNMP_CONFIG_ID);

/* ALTER IKR_DEFINITION */
ALTER TABLE IKR_DEFINITION ADD SD_VALUE VARCHAR(100) NULL;

/* ALTER ALERT_CONDITION */
ALTER TABLE ALERT_CONDITION ADD COND_UNIT_TYPE VARCHAR(50) default 'NUMBER' ;
ALTER TABLE ALERT_CONDITION ADD COND_UNIT VARCHAR(50) default 'NUMBER' ;