DROP TABLE IKR_VERSION;

DROP TABLE CONNECTOR_CONFIG;

DROP TABLE CONNECTOR_CONFIG_ATTRIBUTE;

DROP TABLE CONNECTOR_BINDING;

DROP TABLE METRIC_DOMAIN_CONFIG;

DROP TABLE METRIC_DOMAIN_ITEMS;

DROP TABLE METRIC_DOMAIN_CONFIG_EXTENSION;

DROP TABLE METRIC_DOMAIN_RESOURCE;

DROP TABLE INDIKTOR_ID ;

DROP TABLE IKR_STATIC_DOMAIN;

DROP TRIGGER CONFIG_FIELD_TRIGGER;
DROP SEQUENCE CONFIG_FIELD_ID_SEQ;
DROP TABLE METRIC_DOMAIN_CONFIG_FIELDS ;

DROP TABLE IKR_CATEGORY;

DROP TRIGGER LOGICAL_ENV_TRIGGER;
DROP SEQUENCE LOGICAL_ENV_ID_SEQ;
DROP TABLE LOGICAL_ENV;

DROP TRIGGER IKR_CATEGORY_RESOURCE_TRIGGER;
DROP SEQUENCE IKR_CATEGORY_RESOURCE_ID_SEQ ;
DROP TABLE IKR_CATEGORY_RESOURCE;

DROP TRIGGER MONITOR_TRIGGER;
DROP SEQUENCE MONITOR_ID_SEQ;
DROP TABLE MONITOR;

DROP TABLE MONITOR_ACTIVITY;

DROP TRIGGER MONITOR_SCHEDULER_TRIGGER;
DROP SEQUENCE MONITOR_SCHEDULER_ID_SEQ;
DROP TABLE MONITOR_SCHEDULER;

DROP TRIGGER TASK_SCHEDULER_TRIGGER;
DROP SEQUENCE TASK_SCHEDULER_ID_SEQ;
DROP TABLE TASK_SCHEDULER;

DROP TRIGGER TASK_ATTRIBUTE_TRIGGER;
DROP SEQUENCE TASK_ATTRIBUTE_ID_SEQ;
DROP TABLE TASK_ATTRIBUTE;

DROP TRIGGER TASK_STATIC_DOMAIN_TRIGGER;
DROP SEQUENCE TASK_STATIC_DOMAIN_ID_SEQ;
DROP TABLE TASK_STATIC_DOMAIN;

DROP TRIGGER TASK_ATTRIBUTE_CONFIG_TRIGGER;
DROP SEQUENCE TASK_ATTRIBUTE_CONFIG_ID_SEQ;
DROP TABLE TASK_ATTRIBUTE_CONFIG;

DROP TABLE SCHEDULER_TIME;

DROP TRIGGER SCHEDULER_EXEC_TRIGGER;
DROP SEQUENCE SCHEDULER_EXEC_ID_SEQ;
DROP TABLE SCHEDULER_EXEC;

DROP TRIGGER MONITOR_ATTRIBUTE_TRIGGER;
DROP SEQUENCE MONITOR_ATTRIBUTE_ID_SEQ;
DROP TABLE MONITOR_ATTRIBUTE;

DROP TRIGGER IKR_DEFINITION_TRIGGER;
DROP SEQUENCE IKR_DEFINITION_ID_SEQ;
DROP INDEX IKR_DEFINITION_INST_ENV_IDX;
DROP INDEX IKR_DEFINITION_MONITOR_ID_IDX;
DROP TABLE IKR_DEFINITION;

DROP INDEX IKR_VALUE_IDX;
DROP TABLE IKR_VALUE;

DROP TABLE USER_LOGIN;

DROP TABLE IKR_USER;

DROP TABLE ACCESS_PERM;

DROP TRIGGER ROLE_TRIGGER;
DROP SEQUENCE ROLE_ID_SEQ;
DROP TABLE ROLE;

DROP TABLE ROLE_ACCESS_PERM;

DROP TABLE USER_ROLE;

DROP TABLE ALERT_DEFINITION;

DROP TABLE ALERT_WORKFLOW_FILTER;

DROP TABLE ALERT_VALIDITY;

DROP TRIGGER ALERT_LEVEL_TRIGGER;
DROP SEQUENCE ALERT_LEVEL_ID_SEQ;
DROP TABLE ALERT_LEVEL;

DROP TRIGGER ALERT_GROUP_TRIGGER;
DROP SEQUENCE ALERT_GROUP_ID_SEQ;
DROP TABLE ALERT_GROUP;

DROP TRIGGER ALERT_DOMAIN_TRIGGER;
DROP SEQUENCE ALERT_DOMAIN_ID_SEQ;
DROP TABLE ALERT_DOMAIN;

DROP TRIGGER ALERT_SUB_DOMAIN_TRIGGER;
DROP SEQUENCE ALERT_SUB_DOMAIN_ID_SEQ;
DROP TABLE ALERT_SUB_DOMAIN;

DROP TABLE ALERT_CONDITION;

DROP TABLE ALERT_COMPUTE;

DROP TABLE ALERT_ACTION;

DROP TABLE USER_ALERT_ACTION;

DROP TABLE SNMP_ALERT_ACTION;

DROP TABLE ALERT_EVENT;

DROP TABLE ALERT_EVENT_COMMENT;

DROP TABLE ALERT_EVENT_COMPUTE;

DROP TRIGGER REPORT_CONFIG_TRIGGER;
DROP SEQUENCE REPORT_CONFIG_ID_SEQ;
DROP TABLE REPORT_CONFIG;


DROP TRIGGER REPORT_TYPE_TRIGGER;
DROP SEQUENCE REPORT_TYPE_ID_SEQ;
DROP TABLE REPORT_TYPE;

DROP TRIGGER SNMP_CONFIG_TRIGGER;
DROP SEQUENCE SNMP_CONFIG_ID_SEQ;
DROP TABLE SNMP_CONFIG;