ALTER TABLE SCHEDULER_TIME DROP CONSTRAINT FK_MONITOR_ID;
ALTER TABLE SCHEDULER_TIME DROP CONSTRAINT FK_TASK_SCHEDULER;

delete from IKR_VALUE where IKR_DEFINITION_ID in (select ID from IKR_DEFINITION where IKR_CATEGORY_ID in (select ID from IKR_STATIC_DOMAIN where DOMAIN_VALUE like '%Eden Memory%' or DOMAIN_VALUE like '%Tenured Memory%' or DOMAIN_VALUE like '%Survivor Memory%' or DOMAIN_VALUE like '%Permanent Memory%' or DOMAIN_VALUE like '%Code Cache Memory%'));
delete from IKR_DEFINITION where IKR_CATEGORY_ID in (select ID from IKR_STATIC_DOMAIN where DOMAIN_VALUE like '%Eden Memory%' or DOMAIN_VALUE like '%Tenured Memory%' or DOMAIN_VALUE like '%Survivor Memory%' or DOMAIN_VALUE like '%Permanent Memory%' or DOMAIN_VALUE like '%Code Cache Memory%');
delete from MONITOR_ACTIVITY where IKR_CATEGORY_RESOURCE_ID in (select ID from IKR_CATEGORY_RESOURCE where IKR_STATIC_DOMAIN_ID in (select ID from IKR_STATIC_DOMAIN where DOMAIN_VALUE like '%Eden Memory%' or DOMAIN_VALUE like '%Tenured Memory%' or DOMAIN_VALUE like '%Survivor Memory%' or DOMAIN_VALUE like '%Permanent Memory%' or DOMAIN_VALUE like '%Code Cache Memory%'));
delete from METRIC_DOMAIN_RESOURCE where RESOURCE_NAME in ('JMX_PROCESS_EDEN_MEMORY', 'JMX_PROCESS_TENURED_MEMORY', 'JMX_PROCESS_SURVIVOR_MEMORY', 'JMX_PROCESS_CODE_CACHE_MEMORY', 'JMX_PROCESS_PERMANENT_MEMORY');
delete from IKR_CATEGORY_RESOURCE where IKR_STATIC_DOMAIN_ID in (select id from IKR_STATIC_DOMAIN where DOMAIN_VALUE like '%Eden Memory%' or DOMAIN_VALUE like '%Tenured Memory%' or DOMAIN_VALUE like '%Survivor Memory%' or DOMAIN_VALUE like '%Permanent Memory%' or DOMAIN_VALUE like '%Code Cache Memory%');
delete from IKR_CATEGORY where IKR_STATIC_DOMAIN_ID in (select id from IKR_STATIC_DOMAIN where DOMAIN_VALUE like '%Eden Memory%' or DOMAIN_VALUE like '%Tenured Memory%' or DOMAIN_VALUE like '%Survivor Memory%' or DOMAIN_VALUE like '%Permanent Memory%' or DOMAIN_VALUE like '%Code Cache Memory%');
delete from IKR_STATIC_DOMAIN where DOMAIN_VALUE like '%Eden Memory%' or DOMAIN_VALUE like '%Tenured Memory%' or DOMAIN_VALUE like '%Survivor Memory%' or DOMAIN_VALUE like '%Permanent Memory%' or DOMAIN_VALUE like '%Code Cache Memory%';

UPDATE IKR_VERSION SET SUB=1,VERSION_DATE=to_date('2011/07/18 00:00:00', 'yyyy/mm/dd hh24:mi:ss');