UPDATE IKR_VERSION SET SUB=2,VERSION_DATE=to_date('2011/12/13 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),PATCH_VERSION=3;

TRUNCATE TABLE ALERT_EVENT;
TRUNCATE TABLE ALERT_EVENT_COMMENT;
TRUNCATE TABLE ALERT_EVENT_COMPUTE;

ALTER TABLE ALERT_EVENT ADD ID NUMBER(20) NOT NULL PRIMARY KEY;

ALTER TABLE ALERT_EVENT_COMMENT DROP COLUMN ALERT_DEFINITION_ID;
ALTER TABLE ALERT_EVENT_COMMENT DROP COLUMN EVENT_DATE;
ALTER TABLE ALERT_EVENT_COMMENT ADD ALERT_EVENT_ID NUMBER(20) NOT NULL;

ALTER TABLE ALERT_EVENT_COMPUTE DROP COLUMN ALERT_DEFINITION_ID;
ALTER TABLE ALERT_EVENT_COMPUTE DROP COLUMN EVENT_DATE;
ALTER TABLE ALERT_EVENT_COMPUTE ADD ALERT_EVENT_ID NUMBER(20) NOT NULL;

INSERT INTO INDIKTOR_ID VALUES (1,'AlertEvent');

