UPDATE IKR_VERSION SET SUB=2,VERSION_DATE=to_date('2012/02/03 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),PATCH_VERSION=5;

CREATE TABLE METRIC_DOMAIN_CONFIG_ATTRIBUTE (
		METRIC_DOMAIN_CONFIG_ID NUMBER(20) NOT NULL,
		ATTRIBUTE_KEY VARCHAR(255) NOT NULL,
		ATTRIBUTE_VALUE VARCHAR(255) default NULL,
  	   CONSTRAINT PK_METRIC_DOMAIN_CFG_ATTRS PRIMARY KEY (METRIC_DOMAIN_CONFIG_ID, ATTRIBUTE_KEY)
) TABLESPACE INDIKTOR;

DROP TRIGGER IKR_CATEGORY_RESOURCE_TRIGGER;
DROP SEQUENCE IKR_CATEGORY_RESOURCE_ID_SEQ;

INSERT INTO INDIKTOR_ID VALUES (1000,'IkrCategoryResource');