/*
* CLEAN THREAD_INFO METRIC INFORMATION
*/
delete from IKR_DEFINITION where IKR_CATEGORY_ID in (select IKR_STATIC_DOMAIN_ID from ikr_category_resource where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from MONITOR_ACTIVITY where IKR_CATEGORY_RESOURCE_ID in (select ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_CATEGORY where IKR_STATIC_DOMAIN_ID in (select IKR_STATIC_DOMAIN_ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_STATIC_DOMAIN where ID in (select IKR_STATIC_DOMAIN_ID from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO'));
delete from IKR_CATEGORY_RESOURCE where METRIC_DOMAIN_RESOURCE_ID in (select ID from metric_domain_resource where RESOURCE_NAME = 'THREAD_INFO');
delete from METRIC_DOMAIN_RESOURCE where RESOURCE_NAME = 'THREAD_INFO';


/*
* TABLE MODELE UPGRADE
*/

DROP TABLE IF EXISTS `IKR_VALUE_ARCHIVE`;
CREATE TABLE `IKR_VALUE_ARCHIVE` (
  `ID` bigint(20) unsigned NOT NULL,
  `IKR_DEFINITION_ID` bigint(20) unsigned NOT NULL,
  `CAPTURE_TIME` datetime NOT NULL,
  `VALUE` longtext,
  PRIMARY KEY  (`ID`),
  KEY `IDX_IKR_DEFINITION_ID_ARCH` (`IKR_DEFINITION_ID`),
  KEY `IDX_CAPTURE_TIME_ARCH` USING HASH (`CAPTURE_TIME`)
) ENGINE=MyISAM AUTO_INCREMENT=5899402 DEFAULT CHARSET=latin1;

ALTER TABLE IKR_CATEGORY ADD THRESHOLD double unsigned default '0';
ALTER TABLE IKR_CATEGORY ADD PERSISTENT tinyint(1) default '1';
ALTER TABLE IKR_CATEGORY ADD ARCHIVE tinyint(1) default '1';
ALTER TABLE IKR_CATEGORY ADD SEARCH_INDEXES varchar(4000) default NULL;

ALTER TABLE TASK_SCHEDULER RENAME TO JOB_SCHEDULER;
ALTER TABLE TASK_ATTRIBUTE RENAME TO JOB_SCHEDULER_ATTRIBUTE;
ALTER TABLE TASK_STATIC_DOMAIN RENAME TO JOB_SCHEDULER_STATIC_DOMAIN;
ALTER TABLE TASK_ATTRIBUTE_CONFIG RENAME TO JOB_SCHEDULER_ATTRIBUTE_CONFIG;

ALTER TABLE JOB_SCHEDULER CHANGE TASK_STATIC_DOMAIN_ID JOB_SCHEDULER_STATIC_DOMAIN_ID bigint(20);
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE CHANGE TASK_SCHEDULER_ID JOB_SCHEDULER_ID int(20);
ALTER TABLE JOB_SCHEDULER_STATIC_DOMAIN CHANGE TASK_TYPE JOB_SCHEDULER_TYPE varchar(100);
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG CHANGE TASK_STATIC_DOMAIN_ID JOB_SCHEDULER_STATIC_DOMAIN_ID bigint(20);

ALTER TABLE JOB_SCHEDULER DROP COLUMN ACTION;

ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION tinyint(1) default '0';
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION_VALUE varchar(100) default NULL;

ALTER TABLE SCHEDULER_TIME RENAME TO MONITOR_SCHEDULER_TIME;
ALTER TABLE SCHEDULER_EXEC RENAME TO MONITOR_SCHEDULER_EXEC;

ALTER TABLE MONITOR_SCHEDULER_TIME CHANGE SCHEDULER_ID MONITOR_SCHEDULER_ID int(20) unsigned NOT NULL;
ALTER TABLE MONITOR_SCHEDULER_EXEC CHANGE SCHEDULER_ID MONITOR_SCHEDULER_ID int(20) unsigned NOT NULL;

DROP TABLE IF EXISTS `JOB_SCHEDULER_TIME`;
CREATE TABLE `JOB_SCHEDULER_TIME` (
  `JOB_ID` int(20) unsigned NOT NULL,
  `SCHED_TIME_TYPE` varchar(200) NOT NULL,
  `SCHED_DAY` int(10) unsigned default 0,
  `SCHED_HOUR` int(10) unsigned default 0,
  `SCHED_MIN` int(10) unsigned default 0,
  PRIMARY KEY (`JOB_ID`, `SCHED_TIME_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER_EXEC`;
CREATE TABLE `JOB_SCHEDULER_EXEC` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `JOB_ID` int(20) unsigned NOT NULL,
  `START_TIME` datetime NOT NULL,
  `END_TIME` datetime default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


/*
* TABLE INITIALISATION
*/

INSERT INTO `JOB_SCHEDULER_STATIC_DOMAIN` VALUES (1,'PURGE_TABLE','Ikr Table Purge Scheduler',NULL);

INSERT INTO `JOB_SCHEDULER_ATTRIBUTE_CONFIG` VALUES (1,1,'PURGE_FREQUENCY','Purge Frequency', true, true, 'Day-1:Week-1:Month-1');
INSERT INTO `JOB_SCHEDULER_ATTRIBUTE_CONFIG` VALUES (2,1,'ARCHIVE_NEEDED','Archive Needed ?', true, true, 'true:false');
INSERT INTO `JOB_SCHEDULER_ATTRIBUTE_CONFIG` VALUES (3,1,'VALUES_PER_DAY','Values per Day', true, true, '1:2:4:6:12:24');

INSERT INTO `INDIKTOR_ID` VALUES (1,'IkrValueArchive');

UPDATE IKR_VERSION SET SUB=2,VERSION_DATE='2011-11-02 00:00:00',PATCH_VERSION=1;