UPDATE IKR_VERSION SET SUB=2,VERSION_DATE=to_date('2012/01/17 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),PATCH_VERSION=4;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION DROP COLUMN EXT_ID;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION DROP COLUMN EXTENDED_ID;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION DROP COLUMN EXT_CONNECTOR_TYPE;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION RENAME COLUMN EXT_DESCRIPTION TO DESCRIPTION;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION RENAME COLUMN EXT_CLASSNAME TO CLASSNAME;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION ADD METRIC_DOMAIN_CONFIG_ID NUMBER(20) NOT NULL;
ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION ADD PRIORITY NUMBER(10) NOT NULL;

ALTER TABLE METRIC_DOMAIN_CONFIG_EXTENSION ADD PRIMARY KEY (METRIC_DOMAIN_CONFIG_ID, PRIORITY);

ALTER TABLE METRIC_DOMAIN_ITEMS RENAME TO METRIC_DOMAIN_CONFIG_ITEMS;

CREATE TABLE METRIC_DOMAIN_CONFIG_RESOURCES (
		METRIC_DOMAIN_CONFIG_ID NUMBER(20) NOT NULL,
		METRIC_DOMAIN_RESOURCE_ID NUMBER(20) NOT NULL,
		ENABLED NUMBER(1) default 1,
  	   CONSTRAINT PK_METRIC_DOMAIN_CFG_RSRC PRIMARY KEY (METRIC_DOMAIN_CONFIG_ID, METRIC_DOMAIN_RESOURCE_ID)
) TABLESPACE INDIKTOR;

ALTER TABLE METRIC_DOMAIN_CONFIG ADD SYNC_USE NUMBER(1) default 0;
ALTER TABLE METRIC_DOMAIN_CONFIG_FIELDS ADD FIELD_TYPE VARCHAR(100) default 'inputText';
ALTER TABLE METRIC_DOMAIN_CONFIG_FIELDS ADD FIELD_TYPE_VALUES VARCHAR(1024) default NULL;

ALTER TABLE ALERT_EVENT_COMMENT DROP COLUMN COMMENTS;
ALTER TABLE ALERT_EVENT_COMMENT ADD COMMENTS CLOB;