ALTER TABLE SCHEDULER_TIME DROP CONSTRAINT FK_MONITOR_ID;
ALTER TABLE SCHEDULER_TIME DROP CONSTRAINT FK_TASK_SCHEDULER;

UPDATE IKR_VERSION SET SUB=1,VERSION_DATE=to_date('2011/07/18 00:00:00', 'yyyy/mm/dd hh24:mi:ss');