
INSERT INTO `JOB_SCHEDULER_STATIC_DOMAIN` VALUES (1,'PURGE_TABLE','Ikr Table Purge Scheduler',NULL);

INSERT INTO `JOB_SCHEDULER_ATTRIBUTE_CONFIG` VALUES (1,1,'PURGE_FREQUENCY','Purge Frequency', true, true, 'Day-1:Week-1:Month-1');
INSERT INTO `JOB_SCHEDULER_ATTRIBUTE_CONFIG` VALUES (2,1,'ARCHIVE_NEEDED','Archive Needed ?', true, true, 'true:false');
INSERT INTO `JOB_SCHEDULER_ATTRIBUTE_CONFIG` VALUES (3,1,'VALUES_PER_DAY','Values per Day', true, true, '1:2:4:6:12:24');

INSERT INTO `INDIKTOR_ID` VALUES (1,'IkrValueArchive');