UPDATE IKR_VERSION SET SUB=2,VERSION_DATE='2011-10-31 00:00:00',PATCH_VERSION=1;

DROP TABLE IF EXISTS `IKR_VALUE_ARCHIVE`;
CREATE TABLE `IKR_VALUE_ARCHIVE` (
  `ID` bigint(20) unsigned NOT NULL,
  `IKR_DEFINITION_ID` bigint(20) unsigned NOT NULL,
  `CAPTURE_TIME` datetime NOT NULL,
  `VALUE` longtext,
  PRIMARY KEY  (`ID`),
  KEY `IDX_IKR_DEFINITION_ID_ARCH` (`IKR_DEFINITION_ID`),
  KEY `IDX_CAPTURE_TIME_ARCH` USING HASH (`CAPTURE_TIME`)
) ENGINE=MyISAM AUTO_INCREMENT=5899402 DEFAULT CHARSET=latin1;

ALTER TABLE IKR_CATEGORY ADD THRESHOLD double unsigned default '0';
ALTER TABLE IKR_CATEGORY ADD PERSISTENT tinyint(1) default '1';
ALTER TABLE IKR_CATEGORY ADD ARCHIVE tinyint(1) default '1';

ALTER TABLE TASK_SCHEDULER RENAME TO JOB_SCHEDULER;
ALTER TABLE TASK_ATTRIBUTE RENAME TO JOB_SCHEDULER_ATTRIBUTE;
ALTER TABLE TASK_STATIC_DOMAIN RENAME TO JOB_SCHEDULER_STATIC_DOMAIN;
ALTER TABLE TASK_ATTRIBUTE_CONFIG RENAME TO JOB_SCHEDULER_ATTRIBUTE_CONFIG;

ALTER TABLE JOB_SCHEDULER CHANGE TASK_STATIC_DOMAIN_ID JOB_SCHEDULER_STATIC_DOMAIN_ID bigint(20);
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE CHANGE TASK_SCHEDULER_ID JOB_SCHEDULER_ID int(20);
ALTER TABLE JOB_SCHEDULER_STATIC_DOMAIN CHANGE TASK_TYPE JOB_SCHEDULER_TYPE varchar(100);
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG CHANGE TASK_STATIC_DOMAIN_ID JOB_SCHEDULER_STATIC_DOMAIN_ID bigint(20);

ALTER TABLE JOB_SCHEDULER DROP COLUMN ACTION;

ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION tinyint(1) default '0';
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION_VALUE varchar(100) default NULL;

ALTER TABLE SCHEDULER_TIME RENAME TO MONITOR_SCHEDULER_TIME;
ALTER TABLE SCHEDULER_EXEC RENAME TO MONITOR_SCHEDULER_EXEC;

ALTER TABLE MONITOR_SCHEDULER_TIME CHANGE SCHEDULER_ID MONITOR_SCHEDULER_ID int(20) unsigned NOT NULL;
ALTER TABLE MONITOR_SCHEDULER_EXEC CHANGE SCHEDULER_ID MONITOR_SCHEDULER_ID int(20) unsigned NOT NULL;

DROP TABLE IF EXISTS `JOB_SCHEDULER_TIME`;
CREATE TABLE `JOB_SCHEDULER_TIME` (
  `JOB_ID` int(20) unsigned NOT NULL,
  `SCHED_TIME_TYPE` varchar(200) NOT NULL,
  `SCHED_DAY` int(10) unsigned default 0,
  `SCHED_HOUR` int(10) unsigned default 0,
  `SCHED_MIN` int(10) unsigned default 0,
  PRIMARY KEY (`JOB_ID`, `SCHED_TIME_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `JOB_SCHEDULER_EXEC`;
CREATE TABLE `JOB_SCHEDULER_EXEC` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `JOB_ID` int(20) unsigned NOT NULL,
  `START_TIME` datetime NOT NULL,
  `END_TIME` datetime default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE IKR_CATEGORY ADD SEARCH_INDEXES varchar(4000) default NULL;



