UPDATE IKR_VERSION SET SUB=2,VERSION_DATE=to_date('2011/11/02 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),PATCH_VERSION=1;


CREATE TABLE IKR_VALUE_ARCHIVE (
  	   ID NUMBER(20) NOT NULL PRIMARY KEY,
  	   IKR_DEFINITION_ID NUMBER(20) NOT NULL,
  	   CAPTURE_TIME DATE NOT NULL,
  	   VALUE CLOB
) TABLESPACE INDIKTOR;

CREATE INDEX IKR_VALUE_IDX_ARCH ON IKR_VALUE_ARCHIVE(IKR_DEFINITION_ID,CAPTURE_TIME) LOGGING NOPARALLEL TABLESPACE INDIKTOR;

ALTER TABLE JOB_SCHEDULER DROP COLUMN ACTION;

ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION NUMBER(1) default 0;
ALTER TABLE JOB_SCHEDULER_ATTRIBUTE_CONFIG ADD SELECTION_VALUE VARCHAR(100) default NULL;

ALTER TABLE SCHEDULER_TIME RENAME TO MONITOR_SCHEDULER_TIME;
ALTER TABLE SCHEDULER_EXEC RENAME TO MONITOR_SCHEDULER_EXEC;

ALTER TABLE MONITOR_SCHEDULER_TIME RENAME COLUMN SCHEDULER_ID TO MONITOR_SCHEDULER_ID;
ALTER TABLE MONITOR_SCHEDULER_EXEC RENAME COLUMN SCHEDULER_ID TO MONITOR_SCHEDULER_ID;

CREATE TABLE JOB_SCHEDULER_TIME (
		JOB_ID NUMBER(20) NOT NULL,
		SCHED_TIME_TYPE VARCHAR(200) NOT NULL,
		SCHED_DAY NUMBER(10) default 0,
		SCHED_HOUR NUMBER(10) default 0,
		SCHED_MIN NUMBER(10) default 0,
   CONSTRAINT PK_JOB_SCHEDULER_TIME PRIMARY KEY (JOB_ID, SCHED_TIME_TYPE)
) TABLESPACE INDIKTOR;

CREATE TABLE JOB_SCHEDULER_EXEC (
		ID NUMBER(10) NOT NULL PRIMARY KEY,
		JOB_ID NUMBER(20) NOT NULL,
		START_TIME DATE NOT NULL,
		END_TIME DATE default NULL
) TABLESPACE INDIKTOR;

CREATE SEQUENCE JOB_SCHEDULER_EXEC_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER JOB_SCHEDULER_EXEC_TRIGGER
BEFORE INSERT ON JOB_SCHEDULER_EXEC
for each row
begin
    select JOB_SCHEDULER_EXEC_ID_SEQ.nextval into :new.id from dual;
end;
/

ALTER TABLE IKR_CATEGORY ADD SEARCH_INDEXES varchar(4000) default NULL;

